// AEPS bank list — `code` is the bank_code Eko expects in the AePS Fingpay call.
// The authoritative list is Eko's published sheet; this covers the major banks.
// Add to it as Eko extends coverage.
export type AepsBank = { code: string; name: string };

export const AEPS_BANKS: AepsBank[] = [
  { code: "SBIN", name: "State Bank of India" },
  { code: "HDFC", name: "HDFC Bank" },
  { code: "ICIC", name: "ICICI Bank" },
  { code: "UTIB", name: "Axis Bank" },
  { code: "PUNB", name: "Punjab National Bank" },
  { code: "BARB", name: "Bank of Baroda" },
  { code: "CNRB", name: "Canara Bank" },
  { code: "UBIN", name: "Union Bank of India" },
  { code: "IOBA", name: "Indian Overseas Bank" },
  { code: "IDIB", name: "Indian Bank" },
  { code: "CBIN", name: "Central Bank of India" },
  { code: "MAHB", name: "Bank of Maharashtra" },
  { code: "BKID", name: "Bank of India" },
  { code: "UCBA", name: "UCO Bank" },
  { code: "PSIB", name: "Punjab & Sind Bank" },
  { code: "KKBK", name: "Kotak Mahindra Bank" },
  { code: "INDB", name: "IndusInd Bank" },
  { code: "YESB", name: "Yes Bank" },
  { code: "IDFB", name: "IDFC First Bank" },
  { code: "FDRL", name: "Federal Bank" },
  { code: "SIBL", name: "South Indian Bank" },
  { code: "KARB", name: "Karnataka Bank" },
  { code: "KVBL", name: "Karur Vysya Bank" },
  { code: "TMBL", name: "Tamilnad Mercantile Bank" },
  { code: "CIUB", name: "City Union Bank" },
  { code: "DLXB", name: "Dhanlaxmi Bank" },
  { code: "CSBK", name: "CSB Bank" },
  { code: "RATN", name: "RBL Bank" },
  { code: "BDBL", name: "Bandhan Bank" },
  { code: "AUBL", name: "AU Small Finance Bank" },
  { code: "ESFB", name: "Equitas Small Finance Bank" },
  { code: "UJVN", name: "Ujjivan Small Finance Bank" },
  { code: "JSFB", name: "Jana Small Finance Bank" },
  { code: "SURY", name: "Suryoday Small Finance Bank" },
  { code: "FINO", name: "Fino Payments Bank" },
  { code: "AIRP", name: "Airtel Payments Bank" },
  { code: "IPOS", name: "India Post Payments Bank" },
  { code: "PYTM", name: "Paytm Payments Bank" },
  { code: "APGB", name: "Andhra Pragathi Grameena Bank" },
  { code: "PKGB", name: "Prathama UP Gramin Bank" },
  { code: "KLGB", name: "Kerala Gramin Bank" },
  { code: "KAGB", name: "Karnataka Gramin Bank" },
  { code: "KVGB", name: "Karnataka Vikas Grameena Bank" },
  { code: "MGBL", name: "Maharashtra Gramin Bank" },
  { code: "BGGB", name: "Baroda Gujarat Gramin Bank" },
  { code: "SGBA", name: "Saurashtra Gramin Bank" },
  { code: "TGBL", name: "Telangana Grameena Bank" },
  { code: "APCB", name: "Andhra Pradesh State Co-op Bank" },
  { code: "SVCB", name: "SVC Co-operative Bank" },
  { code: "COSB", name: "Cosmos Co-operative Bank" },
  { code: "ABHY", name: "Abhyudaya Co-operative Bank" },
  { code: "JIOP", name: "Jio Payments Bank" },
  { code: "NSPB", name: "NSDL Payments Bank" },
  { code: "UTKS", name: "Utkarsh Small Finance Bank" },
  { code: "NKGS", name: "NKGSB Co-operative Bank" },
  { code: "TJSB", name: "TJSB Sahakari Bank" },
  { code: "BCBM", name: "Bassein Catholic Co-op Bank" },
  { code: "PMEC", name: "Punjab & Maharashtra Co-op Bank" },
  { code: "JAKA", name: "Jammu & Kashmir Bank" },
  { code: "SRCB", name: "Saraswat Co-operative Bank" },
  { code: "DCBL", name: "DCB Bank" },
  { code: "BACB", name: "Bharat Co-operative Bank" },
];
