import { useMemo, useState, type ChangeEvent } from "react";
import { toast } from "sonner";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Building2, Check, FileText, GraduationCap, Landmark, LockKeyhole, MapPinned, Upload, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type FormState = Record<string, string>;
const steps = [
  { title: "Personal", icon: UserRound }, { title: "Education", icon: GraduationCap },
  { title: "Experience", icon: BriefcaseBusiness }, { title: "Bank", icon: Landmark },
  { title: "Documents", icon: FileText }, { title: "Account", icon: LockKeyhole },
  { title: "Assignment", icon: MapPinned },
];

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) {
  return <label className="space-y-1.5 text-xs font-bold text-foreground">{label}{required && <span className="text-destructive"> *</span>}{children}</label>;
}

export function EmployeeOnboarding({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>({ country: "India", employmentType: "Full-time", role: "Employee", status: "Active" });
  const [files, setFiles] = useState<Record<string, string>>({});
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const input = (key: string, type = "text", placeholder = "") => <Input type={type} value={form[key] ?? ""} placeholder={placeholder} maxLength={type === "password" ? 64 : 120} onChange={(event) => update(key, event.target.value)} />;
  const required: Record<number, string[]> = { 0: ["firstName", "lastName", "email", "phone", "dob"], 1: ["qualification", "institution"], 3: ["accountName", "accountNumber", "ifsc"], 5: ["username", "password"], 6: ["department", "designation", "territory", "manager", "joiningDate"] };
  const invalid = useMemo(() => (required[step] ?? []).filter((key) => !(form[key] ?? "").trim()), [form, step]);
  const next = () => {
    if (invalid.length) { toast.error("Complete all required fields"); return; }
    if (step === 0 && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email ?? "")) { toast.error("Enter a valid email address"); return; }
    if (step === 3 && !/^[A-Z]{4}0[A-Z0-9]{6}$/.test((form.ifsc ?? "").toUpperCase())) { toast.error("Enter a valid 11-character IFSC code"); return; }
    setStep((value) => Math.min(steps.length - 1, value + 1));
  };
  const select = (key: string, placeholder: string, options: string[]) => <Select value={form[key]} onValueChange={(value) => update(key, value)}><SelectTrigger><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem value={option} key={option}>{option}</SelectItem>)}</SelectContent></Select>;
  const file = (key: string, label: string) => <label className="flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-border bg-muted/30 p-3 text-center hover:bg-muted/60"><Upload className="mb-2 h-5 w-5 text-hr" /><span className="text-xs font-bold">{files[key] || label}</span><span className="mt-1 text-[10px] text-muted-foreground">PDF, JPG or PNG · max 5 MB</span><input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event: ChangeEvent<HTMLInputElement>) => { const chosen = event.target.files?.[0]; if (!chosen) return; if (chosen.size > 5 * 1024 * 1024) { toast.error("File must be under 5 MB"); return; } setFiles((current) => ({ ...current, [key]: chosen.name })); }} /></label>;
  const submit = () => { if (invalid.length) { toast.error("Complete all required fields"); return; } toast.success("Employee profile created", { description: `${form.firstName} ${form.lastName} is assigned to ${form.territory}.` }); onOpenChange(false); setStep(0); };

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto p-0">
    <DialogHeader className="border-b border-border px-6 py-5"><DialogTitle>Add employee</DialogTitle><DialogDescription>Create the employee profile, login access, reporting line, and territory assignment.</DialogDescription></DialogHeader>
    <div className="grid min-h-[520px] md:grid-cols-[210px_1fr]"><aside className="border-b border-border bg-muted/30 p-4 md:border-b-0 md:border-r"><p className="mb-3 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Onboarding progress</p><Progress value={((step + 1) / steps.length) * 100} className="mb-5 h-1.5" /><ol className="grid grid-cols-2 gap-1 md:grid-cols-1">{steps.map((item, index) => { const Icon = item.icon; return <li key={item.title}><button type="button" onClick={() => index < step && setStep(index)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-semibold ${index === step ? "bg-hr text-hr-foreground" : index < step ? "text-foreground hover:bg-muted" : "text-muted-foreground"}`}><span className={`grid h-6 w-6 place-items-center rounded-md ${index === step ? "bg-hr-foreground/15" : "bg-background"}`}>{index < step ? <Check className="h-3.5 w-3.5" /> : <Icon className="h-3.5 w-3.5" />}</span>{item.title}</button></li>; })}</ol></aside>
      <div className="p-5 md:p-7"><div className="mb-6"><p className="text-[10px] font-bold uppercase tracking-wider text-hr">Step {step + 1} of {steps.length}</p><h3 className="mt-1 font-display text-xl font-extrabold">{steps[step].title} details</h3></div>
        {step === 0 && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="First name" required>{input("firstName", "text", "Aarav")}</Field><Field label="Middle name">{input("middleName")}</Field><Field label="Last name" required>{input("lastName", "text", "Sharma")}</Field><Field label="Date of birth" required>{input("dob", "date")}</Field><Field label="Gender">{select("gender", "Select", ["Male", "Female", "Non-binary", "Prefer not to say"])}</Field><Field label="Mobile number" required>{input("phone", "tel", "+91 98765 43210")}</Field><Field label="Personal email" required>{input("email", "email", "name@example.com")}</Field><Field label="Emergency contact">{input("emergencyPhone", "tel")}</Field><Field label="Blood group">{select("bloodGroup", "Select", ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"])}</Field><Field label="Current address"><Textarea value={form.address ?? ""} maxLength={300} onChange={(event) => update("address", event.target.value)} /></Field></div>}
        {step === 1 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Highest qualification" required>{select("qualification", "Select qualification", ["10th", "12th", "Diploma", "Bachelor's", "Master's", "Doctorate"])}</Field><Field label="Specialization">{input("specialization", "text", "Finance, Computer Science…")}</Field><Field label="Institution / university" required>{input("institution")}</Field><Field label="Year of passing">{input("passingYear", "number", "2024")}</Field><Field label="Score / grade">{input("grade", "text", "8.4 CGPA")}</Field><Field label="Additional certification">{input("certification")}</Field></div>}
        {step === 2 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Previous employer">{input("employer")}</Field><Field label="Previous designation">{input("previousDesignation")}</Field><Field label="Total experience (years)">{input("experience", "number", "3")}</Field><Field label="Employment period">{input("employmentPeriod", "text", "Jan 2022 – May 2026")}</Field><Field label="Last drawn CTC">{input("lastCtc", "text", "₹6,50,000")}</Field><Field label="Reason for leaving">{input("leavingReason")}</Field><Field label="Key responsibilities"><Textarea value={form.responsibilities ?? ""} maxLength={500} onChange={(event) => update("responsibilities", event.target.value)} /></Field></div>}
        {step === 3 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Account holder name" required>{input("accountName")}</Field><Field label="Bank name">{input("bankName")}</Field><Field label="Account number" required>{input("accountNumber")}</Field><Field label="Confirm account number" required>{input("confirmAccountNumber")}</Field><Field label="IFSC code" required>{input("ifsc", "text", "HDFC0001234")}</Field><Field label="Branch">{input("branch")}</Field><Field label="PAN number">{input("pan", "text", "ABCDE1234F")}</Field><Field label="UAN / PF number">{input("uan")}</Field></div>}
        {step === 4 && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{file("photo", "Profile photograph")}{file("aadhaar", "Aadhaar card")}{file("panDoc", "PAN card")}{file("educationDoc", "Education certificate")}{file("experienceDoc", "Experience letter")}{file("bankProof", "Cancelled cheque")}</div>}
        {step === 5 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Username" required>{input("username", "text", "firstname.lastname")}</Field><Field label="Temporary password" required>{input("password", "password", "Minimum 8 characters")}</Field><Field label="System role">{select("role", "Select role", ["Employee", "Team Lead", "Manager", "HR Executive", "Payroll Executive"])}</Field><Field label="Official email">{input("officialEmail", "email", "name@bharatone.in")}</Field><div className="rounded-lg border border-border bg-muted/30 p-4 sm:col-span-2"><p className="text-xs font-bold">Access policy</p><p className="mt-1 text-xs text-muted-foreground">The employee will receive a secure activation link and must change the temporary password on first login.</p></div></div>}
        {step === 6 && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Department" required>{select("department", "Select", ["Technology", "Operations", "Finance", "Sales", "Quality", "Human Resources"])}</Field><Field label="Designation" required>{input("designation", "text", "Territory Officer")}</Field><Field label="Employment type">{select("employmentType", "Select", ["Full-time", "Part-time", "Contract", "Intern"])}</Field><Field label="Territory" required>{select("territory", "Assign territory", ["Bengaluru Urban", "Mysuru", "Mumbai Central", "Hyderabad North", "Kochi", "Pan India"] )}</Field><Field label="Reporting manager" required>{select("manager", "Select manager", ["Ananya Rao", "Arjun Kumar", "Meera Nair", "Priya Shah"])}</Field><Field label="Office / branch">{select("office", "Select branch", ["Bengaluru HQ", "Mumbai Office", "Hyderabad Office", "Kochi Office"])}</Field><Field label="Joining date" required>{input("joiningDate", "date")}</Field><Field label="Employee status">{select("status", "Select", ["Active", "Probation", "Joining pending"])}</Field></div><div className="rounded-xl border border-border bg-muted/30 p-4"><div className="flex items-center gap-2"><Building2 className="h-4 w-4 text-hr" /><p className="text-sm font-bold">Profile summary</p></div><div className="mt-3 grid gap-3 text-xs sm:grid-cols-3"><p><span className="block text-muted-foreground">Employee</span>{form.firstName || "—"} {form.lastName || ""}</p><p><span className="block text-muted-foreground">Access</span>{form.username || "—"} · {form.role}</p><p><span className="block text-muted-foreground">Assignment</span>{form.department || "—"} · {form.territory || "—"}</p></div></div></div>}
      </div></div>
    <DialogFooter className="border-t border-border px-6 py-4"><Button variant="outline" onClick={() => step === 0 ? onOpenChange(false) : setStep((value) => value - 1)}>{step > 0 && <ArrowLeft />} {step === 0 ? "Cancel" : "Back"}</Button>{step < steps.length - 1 ? <Button className="bg-hr text-hr-foreground hover:bg-hr/90" onClick={next}>Save & continue <ArrowRight /></Button> : <Button className="bg-hr text-hr-foreground hover:bg-hr/90" onClick={submit}><Check /> Create employee</Button>}</DialogFooter>
  </DialogContent></Dialog>;
}