import { useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BadgeCheck, Ban,
  Building2, CheckCircle2, CircleDollarSign, Clock3, Download, Eye, Filter,
  Gauge, Landmark, LockKeyhole, MoreHorizontal, Plus, RefreshCw, Search,
  Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Store, Users, WalletCards,
  Zap, type LucideIcon,
} from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { downloadCsv, safeFileName } from "@/lib/admin-actions";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

type ModuleMetric = { label: string; value: string; delta: string; direction?: "up" | "down"; icon: LucideIcon };
type ModuleConfig = {
  eyebrow: string;
  description: string;
  primaryAction: string;
  metrics: ModuleMetric[];
  chartTitle: string;
  chartSub: string;
  chartType?: "area" | "bar";
  columns: string[];
  rows: string[][];
  queueTitle: string;
  queue: { title: string; detail: string; tone: "success" | "warning" | "danger" | "neutral" }[];
};

const baseMetrics: ModuleMetric[] = [
  { label: "Total records", value: "12,846", delta: "+8.2%", icon: Gauge },
  { label: "Active now", value: "8,412", delta: "+126", icon: Activity },
  { label: "Pending action", value: "116", delta: "-14.7%", direction: "down", icon: Clock3 },
  { label: "Success rate", value: "98.7%", delta: "+1.4%", icon: BadgeCheck },
];

const makeConfig = (overrides: Partial<ModuleConfig>): ModuleConfig => ({
  eyebrow: "Platform operations",
  description: "Monitor, investigate and control this operational domain from a unified workspace.",
  primaryAction: "Create new",
  metrics: baseMetrics,
  chartTitle: "Operational trend",
  chartSub: "Last seven reporting periods",
  columns: ["Reference", "Entity", "Owner", "Status", "Updated"],
  rows: [
    ["BO-82941", "Bharat Digital Services", "Anita Rao", "Active", "2 min ago"],
    ["BO-82940", "Kaveri One Center", "Vikram Singh", "Review", "8 min ago"],
    ["BO-82939", "Shree Balaji Store", "Neha Patel", "Pending", "16 min ago"],
    ["BO-82938", "Namma Seva Point", "Arjun Kumar", "Active", "24 min ago"],
    ["BO-82937", "Vijaya Enterprises", "Sara Khan", "Blocked", "41 min ago"],
  ],
  queueTitle: "Action intelligence",
  queue: [
    { title: "SLA threshold approaching", detail: "18 records need review in the next 30 minutes", tone: "warning" },
    { title: "Automation completed", detail: "284 records reconciled without exceptions", tone: "success" },
    { title: "Policy exception detected", detail: "One high-priority case requires approval", tone: "danger" },
  ],
  ...overrides,
});

const MODULES: Record<string, ModuleConfig> = {
  "Live Operations": makeConfig({ eyebrow: "Network operations center", description: "Observe transaction flow, service latency and incident signals across the live BharatOne network.", primaryAction: "Open incident", chartTitle: "Live transaction throughput", chartSub: "Requests per minute with success envelope", metrics: [
    { label: "Transactions / min", value: "1,284", delta: "+12.8%", icon: Activity }, { label: "Success rate", value: "98.74%", delta: "+0.8%", icon: BadgeCheck }, { label: "P95 latency", value: "184ms", delta: "-22ms", direction: "down", icon: Gauge }, { label: "Open incidents", value: "03", delta: "1 critical", icon: AlertTriangle },
  ], columns: ["Event ID", "Service", "Partner", "Amount", "State", "Latency"], rows: [["TX-92841", "AEPS Withdrawal", "Balaji Store", "₹8,500", "Success", "92ms"], ["TX-92840", "DMT Transfer", "Kaveri Digital", "₹24,000", "Processing", "148ms"], ["TX-92839", "BBPS Power", "Vijaya Services", "₹3,260", "Success", "104ms"], ["TX-92838", "AEPS Balance", "Namma Center", "—", "Review", "286ms"], ["TX-92837", "Recharge", "One Digital", "₹749", "Failed", "412ms"]], queueTitle: "Incident stream" }),
  "User Management": makeConfig({ eyebrow: "Identity command", description: "Control the complete user lifecycle, access posture, verification state and organization membership.", primaryAction: "Add user", chartTitle: "User acquisition & activation", metrics: [{ label: "Total users", value: "48,296", delta: "+9.4%", icon: Users }, { label: "Active today", value: "18,402", delta: "+6.1%", icon: Activity }, { label: "Suspended", value: "128", delta: "-12", direction: "down", icon: Ban }, { label: "Verified", value: "94.8%", delta: "+2.3%", icon: BadgeCheck }], columns: ["User ID", "Name", "Role", "Access state", "Last active"], rows: [["USR-41028", "Anita Rao", "Distributor", "Active", "Now"], ["USR-41027", "Vikram Singh", "Retailer", "Active", "3 min ago"], ["USR-41026", "Neha Patel", "BDE", "Review", "18 min ago"], ["USR-41025", "Arjun Kumar", "Retailer", "Suspended", "2 hours ago"], ["USR-41024", "Sara Khan", "Accountant", "Active", "Yesterday"]] }),
  "KYC Approvals": makeConfig({ eyebrow: "Compliance review desk", description: "Risk-prioritized document verification with SLA controls, anomaly signals and reviewer assignment.", primaryAction: "Start review", chartTitle: "Approval velocity", metrics: [{ label: "Pending review", value: "116", delta: "34 priority", icon: Clock3 }, { label: "Approved today", value: "284", delta: "+18.2%", icon: BadgeCheck }, { label: "Avg. review time", value: "4m 18s", delta: "-42s", direction: "down", icon: Gauge }, { label: "Flagged", value: "18", delta: "6 high risk", icon: AlertTriangle }], columns: ["Application", "Applicant", "Risk score", "Documents", "SLA"], rows: [["KYC-8291", "Ramesh Traders", "Low · 12", "6 / 6", "18m left"], ["KYC-8290", "City One Point", "High · 86", "5 / 6", "Breached"], ["KYC-8289", "Namma Digital", "Medium · 48", "6 / 6", "44m left"], ["KYC-8288", "Saanvi Services", "Low · 09", "6 / 6", "1h 12m"], ["KYC-8287", "Patel Enterprise", "High · 78", "4 / 6", "Breached"]], queueTitle: "Risk review queue" }),
  "Applications": makeConfig({ eyebrow: "Application orchestration", description: "Track applications from intake to activation with automated validation and exception handling.", primaryAction: "New application", chartTitle: "Application funnel", columns: ["Application", "Business", "Product", "Stage", "Age"], rows: [["APP-72941", "Balaji Store", "Retailer", "Verification", "18 min"], ["APP-72940", "Kaveri Digital", "Distributor", "Underwriting", "2 hours"], ["APP-72939", "Vijaya Services", "AEPS", "Approved", "4 hours"], ["APP-72938", "Namma Center", "Retailer", "Documents", "1 day"], ["APP-72937", "One Digital", "DMT", "Activated", "2 days"]] }),
  "Retailer Network": makeConfig({ eyebrow: "Distribution intelligence", description: "Map retailer health, activation quality, service adoption and regional expansion in one operating view.", primaryAction: "Onboard retailer", chartTitle: "Network growth", metrics: [{ label: "Active retailers", value: "8,412", delta: "+126", icon: Store }, { label: "Transacting today", value: "6,894", delta: "81.9%", icon: Activity }, { label: "New this month", value: "428", delta: "+22.4%", icon: Plus }, { label: "At-risk centers", value: "84", delta: "-9", direction: "down", icon: AlertTriangle }], columns: ["Retailer", "District", "Services", "30D volume", "Health"], rows: [["RT-20482", "Mysuru", "6 active", "₹8.4L", "Excellent"], ["RT-20481", "Bengaluru", "4 active", "₹6.2L", "Good"], ["RT-20480", "Hubballi", "5 active", "₹4.8L", "Good"], ["RT-20479", "Mandya", "2 active", "₹1.2L", "At risk"], ["RT-20478", "Belagavi", "6 active", "₹7.1L", "Excellent"]] }),
  "Roles & Permissions": makeConfig({ eyebrow: "Zero-trust access control", description: "Design least-privilege roles, inspect permission drift and govern sensitive administrative access.", primaryAction: "Create role", chartTitle: "Access policy coverage", metrics: [{ label: "Custom roles", value: "18", delta: "+2 this month", icon: LockKeyhole }, { label: "Policy bindings", value: "284", delta: "+14", icon: ShieldCheck }, { label: "Privileged users", value: "12", delta: "0 changes", icon: Users }, { label: "Access alerts", value: "03", delta: "Needs review", icon: AlertTriangle }], columns: ["Role", "Members", "Permissions", "Risk", "Modified"], rows: [["Super Admin", "2", "All platform", "Critical", "Today"], ["Finance Controller", "8", "24 grants", "High", "Yesterday"], ["Regional Manager", "42", "18 grants", "Medium", "2 days ago"], ["KYC Reviewer", "26", "11 grants", "Low", "5 days ago"], ["Support Agent", "84", "8 grants", "Low", "1 week ago"]], queueTitle: "Access recommendations" }),
  "Wallet Control": makeConfig({ eyebrow: "Treasury operations", description: "Control wallet liquidity, limits, holds and fund movements with maker-checker governance.", primaryAction: "Fund wallet", chartTitle: "Liquidity movement", metrics: [{ label: "Total wallet pool", value: "₹2.84Cr", delta: "+4.8%", icon: WalletCards }, { label: "Available liquidity", value: "₹2.21Cr", delta: "77.8%", icon: CircleDollarSign }, { label: "Funds on hold", value: "₹18.4L", delta: "12 wallets", icon: LockKeyhole }, { label: "Low balance", value: "28", delta: "Needs action", icon: AlertTriangle }], columns: ["Wallet", "Account", "Balance", "Daily limit", "State"], rows: [["WLT-84201", "Kaveri Digital", "₹8,42,180", "₹12L", "Healthy"], ["WLT-84200", "Balaji Store", "₹2,18,420", "₹5L", "Healthy"], ["WLT-84199", "Namma Center", "₹18,840", "₹3L", "Low balance"], ["WLT-84198", "Vijaya Services", "₹4,82,100", "₹8L", "On hold"], ["WLT-84197", "One Digital", "₹6,10,220", "₹10L", "Healthy"]], queueTitle: "Treasury actions" }),
  "Revenue Analytics": makeConfig({ eyebrow: "Financial intelligence", description: "Analyze gross volume, net revenue, margin contribution and service economics across every business dimension.", primaryAction: "Build report", chartTitle: "Revenue & margin trend", metrics: [{ label: "Gross revenue", value: "₹84.2L", delta: "+18.6%", icon: CircleDollarSign }, { label: "Net revenue", value: "₹31.8L", delta: "+14.2%", icon: Landmark }, { label: "Contribution margin", value: "37.8%", delta: "+2.1%", icon: Gauge }, { label: "Forecast", value: "₹1.12Cr", delta: "94% confidence", icon: Sparkles }], columns: ["Service", "Gross volume", "Revenue", "Margin", "Growth"], rows: [["AEPS", "₹4.82Cr", "₹31.2L", "42.8%", "+22.4%"], ["DMT", "₹3.16Cr", "₹22.8L", "34.2%", "+16.1%"], ["BBPS", "₹1.42Cr", "₹14.6L", "31.8%", "+9.8%"], ["Recharge", "₹82.4L", "₹8.4L", "28.4%", "+7.2%"], ["PAN", "₹18.2L", "₹4.8L", "51.2%", "+18.9%"]] }),
  "Settlements": makeConfig({ eyebrow: "Settlement control room", description: "Reconcile batches, investigate variances and release settlements through controlled approval workflows.", primaryAction: "Run settlement", chartTitle: "Settlement throughput", metrics: [{ label: "Settled today", value: "₹3.42Cr", delta: "+12.8%", icon: Landmark }, { label: "In processing", value: "₹48.2L", delta: "14 batches", icon: RefreshCw }, { label: "Variance", value: "₹12,480", delta: "3 exceptions", icon: AlertTriangle }, { label: "Success rate", value: "99.84%", delta: "+0.12%", icon: BadgeCheck }], columns: ["Batch", "Region", "Gross amount", "Variance", "State"], rows: [["STL-240615-KA", "Karnataka", "₹84.2L", "₹0", "Completed"], ["STL-240615-TN", "Tamil Nadu", "₹72.8L", "₹12,480", "Review"], ["STL-240615-MH", "Maharashtra", "₹68.1L", "₹0", "Processing"], ["STL-240615-TS", "Telangana", "₹54.6L", "₹0", "Completed"], ["STL-240615-KL", "Kerala", "₹42.4L", "₹0", "Queued"]], queueTitle: "Reconciliation queue" }),
  "Risk & Fraud": makeConfig({ eyebrow: "Risk intelligence engine", description: "Investigate behavioral anomalies, transaction velocity and linked entities using explainable risk signals.", primaryAction: "Create rule", chartTitle: "Risk signal intensity", metrics: [{ label: "Risk events", value: "284", delta: "+18 today", icon: ShieldCheck }, { label: "Critical alerts", value: "08", delta: "2 unresolved", icon: AlertTriangle }, { label: "Value protected", value: "₹18.4L", delta: "+₹3.2L", icon: CircleDollarSign }, { label: "False-positive rate", value: "1.8%", delta: "-0.4%", direction: "down", icon: BadgeCheck }], columns: ["Alert", "Entity", "Signal", "Exposure", "Risk"], rows: [["RSK-48291", "RT-2041", "Wallet velocity", "₹2.8L", "Critical"], ["RSK-48290", "USR-1842", "Device mismatch", "₹84,000", "High"], ["RSK-48289", "RT-9812", "Geo anomaly", "₹42,800", "Medium"], ["RSK-48288", "USR-4820", "Repeated failure", "₹18,400", "Low"], ["RSK-48287", "RT-1048", "Linked accounts", "₹1.2L", "High"]], queueTitle: "Investigation queue" }),
  "Service Catalog": makeConfig({ eyebrow: "Product operations", description: "Configure services, provider routing, pricing, availability and rollout controls across the network.", primaryAction: "Add service", chartTitle: "Service adoption", metrics: [{ label: "Live services", value: "42", delta: "+4 this quarter", icon: Zap }, { label: "Provider routes", value: "86", delta: "98.4% healthy", icon: Activity }, { label: "Avg. availability", value: "99.92%", delta: "+0.08%", icon: Gauge }, { label: "Degraded", value: "02", delta: "Being monitored", icon: AlertTriangle }], columns: ["Service", "Provider", "Availability", "Success rate", "State"], rows: [["AEPS Withdrawal", "Primary + failover", "99.98%", "98.8%", "Live"], ["DMT", "3 routes", "99.92%", "98.2%", "Live"], ["BBPS", "Biller network", "99.88%", "97.9%", "Degraded"], ["Mobile Recharge", "2 routes", "99.96%", "99.1%", "Live"], ["PAN Services", "Primary", "99.74%", "96.8%", "Maintenance"]] }),
  "Support Center": makeConfig({ eyebrow: "Customer operations", description: "Orchestrate omnichannel cases, SLA performance, escalations and agent workload from one service desk.", primaryAction: "New ticket", chartTitle: "Ticket demand & resolution", metrics: [{ label: "Open tickets", value: "284", delta: "-8.2%", direction: "down", icon: Activity }, { label: "SLA at risk", value: "18", delta: "6 urgent", icon: AlertTriangle }, { label: "First response", value: "3m 42s", delta: "-28s", direction: "down", icon: Clock3 }, { label: "CSAT", value: "4.82 / 5", delta: "+0.14", icon: BadgeCheck }], columns: ["Ticket", "Customer", "Category", "Priority", "SLA"], rows: [["TKT-48291", "Balaji Store", "Settlement", "Urgent", "12m left"], ["TKT-48290", "Kaveri Digital", "AEPS", "High", "48m left"], ["TKT-48289", "Namma Center", "Wallet", "Medium", "2h 18m"], ["TKT-48288", "Vijaya Services", "KYC", "Low", "4h 42m"], ["TKT-48287", "One Digital", "Access", "High", "Breached"]], queueTitle: "Escalation queue" }),
  "System Settings": makeConfig({ eyebrow: "Platform configuration", description: "Govern environment-wide policies, integrations, feature controls and audit-safe configuration changes.", primaryAction: "New configuration", chartTitle: "Configuration activity", metrics: [{ label: "Active policies", value: "148", delta: "+6 this month", icon: Settings2 }, { label: "Integrations", value: "24", delta: "23 healthy", icon: Zap }, { label: "Feature controls", value: "38", delta: "12 targeted", icon: SlidersHorizontal }, { label: "Audit exceptions", value: "01", delta: "Review required", icon: AlertTriangle }], columns: ["Configuration", "Scope", "Value", "Changed by", "State"], rows: [["Transaction limits", "Global", "Policy v4.2", "Super Admin", "Active"], ["KYC SLA", "Operations", "4 hours", "Compliance", "Active"], ["Settlement window", "Finance", "T+1", "Controller", "Active"], ["AEPS rollout", "Karnataka", "100%", "Product Admin", "Active"], ["Maintenance mode", "BBPS", "Off", "Platform Ops", "Scheduled"]], queueTitle: "Governance checks" }),
};

const TREND = [{ name: "Mon", primary: 42, secondary: 31 }, { name: "Tue", primary: 54, secondary: 38 }, { name: "Wed", primary: 48, secondary: 41 }, { name: "Thu", primary: 68, secondary: 48 }, { name: "Fri", primary: 74, secondary: 58 }, { name: "Sat", primary: 63, secondary: 52 }, { name: "Sun", primary: 82, secondary: 64 }];

function StatusPill({ value }: { value: string }) {
  const normalized = value.toLowerCase();
  const tone = normalized.includes("active") || normalized.includes("success") || normalized.includes("completed") || normalized.includes("healthy") || normalized.includes("excellent") || normalized === "live"
    ? "bg-admin-success-soft text-admin-success"
    : normalized.includes("critical") || normalized.includes("failed") || normalized.includes("blocked") || normalized.includes("breached") || normalized.includes("suspended")
      ? "bg-admin-danger-soft text-admin-danger"
      : "bg-admin-warning-soft text-admin-warning";
  return <span className={cn("inline-flex rounded-full px-2 py-1 text-[9px] font-extrabold", tone)}>{value}</span>;
}

export function AdminModuleView({ module }: { module: string }) {
  const config = MODULES[module] ?? makeConfig({});
  const [query, setQuery] = useState("");
  const [period, setPeriod] = useState("7d");
  const [statusFilter, setStatusFilter] = useState("All");
  const [page, setPage] = useState(0);
  const [selected, setSelected] = useState<{ title: string; detail: string } | null>(null);
  const [actionOpen, setActionOpen] = useState(false);
  const [columnsOpen, setColumnsOpen] = useState(false);
  const [visibleColumns, setVisibleColumns] = useState(() => config.columns.map(() => true));
  const statuses = useMemo(() => ["All", ...Array.from(new Set(config.rows.map((row) => row.at(-1) ?? "")))], [config.rows]);
  const filteredRows = useMemo(() => config.rows.filter((row) => {
    const matchesQuery = row.join(" ").toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (statusFilter === "All" || row.at(-1) === statusFilter);
  }), [config.rows, query, statusFilter]);
  const pageSize = 3;
  const pageCount = Math.max(1, Math.ceil(filteredRows.length / pageSize));
  const pageRows = filteredRows.slice(page * pageSize, page * pageSize + pageSize);

  useEffect(() => {
    setQuery("");
    setStatusFilter("All");
    setPage(0);
    setVisibleColumns(config.columns.map(() => true));
  }, [config.columns, module]);

  const openDetails = (title: string, detail: string) => setSelected({ title, detail });
  const performPrimaryAction = () => {
    setActionOpen(false);
    toast.success(`${config.primaryAction} started`, { description: `${module} workflow is ready for the next step.` });
  };

  return (
    <div className="space-y-5">
      <section className="overflow-hidden rounded-2xl border border-border bg-admin-panel text-admin-panel-foreground shadow-elev">
        <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center lg:p-6">
          <div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[0.22em] text-admin">{config.eyebrow}</p><h2 className="mt-2 font-display text-xl font-extrabold sm:text-2xl">{module}</h2><p className="mt-2 max-w-2xl text-xs leading-relaxed text-admin-panel-foreground/55">{config.description}</p></div>
          <div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" className="border-admin-panel-foreground/15 bg-admin-panel-foreground/5 text-admin-panel-foreground hover:bg-admin-panel-foreground/10 hover:text-admin-panel-foreground" onClick={() => { downloadCsv(`${safeFileName(module)}.csv`, config.columns, filteredRows); toast.success("Export downloaded"); }}><Download /> Export</Button><Button size="sm" className="bg-admin text-admin-foreground hover:bg-admin/90" onClick={() => setActionOpen(true)}><Plus />{config.primaryAction}</Button></div>
        </div>
        <div className="grid grid-cols-2 border-t border-admin-panel-foreground/10 lg:grid-cols-4">{config.metrics.map((metric) => { const Icon = metric.icon; const DeltaIcon = metric.direction === "down" ? ArrowDownRight : ArrowUpRight; return <div key={metric.label} className="border-r border-admin-panel-foreground/10 p-4 last:border-r-0"><div className="flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-wider text-admin-panel-foreground/40">{metric.label}</p><Icon className="h-4 w-4 text-admin-panel-foreground/35" /></div><p className="mt-2 font-display text-xl font-extrabold sm:text-2xl">{metric.value}</p><p className={cn("mt-1 flex items-center gap-1 text-[9px] font-bold", metric.direction === "down" ? "text-admin-success" : "text-admin") }><DeltaIcon className="h-3 w-3" />{metric.delta}</p></div>; })}</div>
      </section>

      <section className="grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,.7fr)]">
        <div className="rounded-2xl border border-border bg-card p-4 shadow-soft lg:p-5"><div className="flex items-start justify-between"><div><h3 className="text-sm font-extrabold">{config.chartTitle}</h3><p className="text-[10px] text-muted-foreground">{config.chartSub} · {period.toUpperCase()}</p></div><Tabs value={period} onValueChange={setPeriod}><TabsList className="h-8"><TabsTrigger value="24h" className="text-[9px]">24H</TabsTrigger><TabsTrigger value="7d" className="text-[9px]">7D</TabsTrigger><TabsTrigger value="30d" className="text-[9px]">30D</TabsTrigger></TabsList></Tabs></div><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%">{config.chartType === "bar" ? <BarChart data={TREND}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={10} /><YAxis axisLine={false} tickLine={false} fontSize={10} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid var(--border)", fontSize: 11 }} /><Bar dataKey="primary" fill="var(--admin)" radius={[5, 5, 0, 0]} /><Bar dataKey="secondary" fill="var(--admin-muted)" radius={[5, 5, 0, 0]} /></BarChart> : <AreaChart data={TREND}><defs><linearGradient id={`module-${module.replaceAll(" ", "-")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--admin)" stopOpacity={0.35} /><stop offset="100%" stopColor="var(--admin)" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={10} /><YAxis axisLine={false} tickLine={false} fontSize={10} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid var(--border)", fontSize: 11 }} /><Area type="monotone" dataKey="primary" stroke="var(--admin)" strokeWidth={2.5} fill={`url(#module-${module.replaceAll(" ", "-")})`} /><Area type="monotone" dataKey="secondary" stroke="var(--india-green)" strokeWidth={2} fill="transparent" /></AreaChart>}</ResponsiveContainer></div></div>
        <div className="rounded-2xl border border-border bg-card p-4 shadow-soft"><div className="flex items-center justify-between"><div><h3 className="text-sm font-extrabold">{config.queueTitle}</h3><p className="text-[10px] text-muted-foreground">Prioritized by operational impact</p></div><Sparkles className="h-4 w-4 text-admin" /></div><div className="mt-4 space-y-2.5">{config.queue.map((item, index) => <div key={item.title} className="rounded-xl border border-border p-3"><div className="flex items-start gap-3"><span className={cn("grid h-8 w-8 shrink-0 place-items-center rounded-lg text-[10px] font-extrabold", item.tone === "success" ? "bg-admin-success-soft text-admin-success" : item.tone === "danger" ? "bg-admin-danger-soft text-admin-danger" : item.tone === "warning" ? "bg-admin-warning-soft text-admin-warning" : "bg-admin-soft text-admin")}>0{index + 1}</span><div className="min-w-0"><p className="text-[11px] font-extrabold">{item.title}</p><p className="mt-1 text-[9px] leading-relaxed text-muted-foreground">{item.detail}</p></div></div><div className="mt-3 flex gap-2"><Button variant="outline" size="sm" className="h-7 flex-1 text-[9px]" onClick={() => openDetails(item.title, item.detail)}><Eye /> Inspect</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-7 w-7"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => toast.success("Assigned to you")}>Assign to me</DropdownMenuItem><DropdownMenuItem onClick={() => toast.success("Marked resolved")}>Mark resolved</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>)}</div><Button variant="outline" size="sm" className="mt-3 w-full" onClick={() => { setQuery(""); setStatusFilter("All"); document.getElementById("admin-records")?.scrollIntoView({ behavior: "smooth" }); }}>Open full queue <ArrowUpRight /></Button></div>
      </section>

      <section id="admin-records" className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft"><div className="grid gap-3 border-b border-border p-4 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="relative min-w-0"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder={`Search ${module.toLowerCase()}…`} className="pl-9" /></div><div className="flex gap-2"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm"><Filter /> {statusFilter === "All" ? "Filter" : statusFilter}</Button></DropdownMenuTrigger><DropdownMenuContent align="end">{statuses.map((status) => <DropdownMenuItem key={status} onClick={() => { setStatusFilter(status); setPage(0); }}>{status}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><Button variant="outline" size="sm" onClick={() => setColumnsOpen(true)}><SlidersHorizontal /> Columns</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-muted/45 text-[9px] font-extrabold uppercase tracking-wider text-muted-foreground"><tr>{config.columns.map((column, index) => visibleColumns[index] && <th key={column} className="px-4 py-3">{column}</th>)}<th className="w-12 px-4 py-3" /></tr></thead><tbody className="divide-y divide-border">{pageRows.map((row, rowIndex) => <tr key={`${row[0]}-${rowIndex}`} className="text-[11px] transition hover:bg-muted/30">{row.map((cell, cellIndex) => visibleColumns[cellIndex] && <td key={`${cell}-${cellIndex}`} className={cn("px-4 py-3", cellIndex === 0 && "font-mono font-bold", cellIndex === 1 && "font-semibold")}>{cellIndex === row.length - 1 ? <StatusPill value={cell} /> : cell}</td>)}<td className="px-4 py-3"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-7 w-7"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => openDetails(row[0], row.join(" · "))}>View details</DropdownMenuItem><DropdownMenuItem onClick={() => toast.success(`${row[0]} assigned to you`)}>Assign to me</DropdownMenuItem></DropdownMenuContent></DropdownMenu></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border px-4 py-3"><p className="text-[9px] text-muted-foreground">Showing {pageRows.length} of {filteredRows.length} matching records · Page {page + 1} of {pageCount}</p><div className="flex gap-1"><Button variant="outline" size="sm" className="h-7 text-[9px]" disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))}>Previous</Button><Button variant="outline" size="sm" className="h-7 text-[9px]" disabled={page + 1 >= pageCount} onClick={() => setPage((value) => Math.min(pageCount - 1, value + 1))}>Next</Button></div></div></section>

      <Dialog open={actionOpen} onOpenChange={setActionOpen}><DialogContent><DialogHeader><DialogTitle>{config.primaryAction}</DialogTitle><DialogDescription>Start a new {module.toLowerCase()} workflow. This opens the operational process and records the initiation time.</DialogDescription></DialogHeader><div className="rounded-xl border border-border bg-muted/40 p-4 text-xs"><p className="font-bold">Workflow owner</p><p className="mt-1 text-muted-foreground">Super Admin · Immediate priority</p></div><DialogFooter><Button variant="outline" onClick={() => setActionOpen(false)}>Cancel</Button><Button onClick={performPrimaryAction}>Continue</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.detail}</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-muted/50 p-3"><p className="text-muted-foreground">Module</p><p className="mt-1 font-bold">{module}</p></div><div className="rounded-xl bg-muted/50 p-3"><p className="text-muted-foreground">Owner</p><p className="mt-1 font-bold">Operations team</p></div></div><DialogFooter><Button onClick={() => setSelected(null)}>Done</Button></DialogFooter></DialogContent></Dialog>
      <Dialog open={columnsOpen} onOpenChange={setColumnsOpen}><DialogContent><DialogHeader><DialogTitle>Visible columns</DialogTitle><DialogDescription>Choose which fields appear in the operational table.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-2">{config.columns.map((column, index) => <Button key={column} variant={visibleColumns[index] ? "secondary" : "outline"} onClick={() => setVisibleColumns((current) => current.map((value, itemIndex) => itemIndex === index ? !value : value))}>{visibleColumns[index] ? <CheckCircle2 /> : null}{column}</Button>)}</div><DialogFooter><Button onClick={() => setColumnsOpen(false)}>Apply</Button></DialogFooter></DialogContent></Dialog>
    </div>
  );
}