import { useMemo, useState } from "react";
import { toast } from "sonner";
import { AlarmClock, CalendarClock, CheckCircle2, ClipboardCheck, Clock3, FileText, Headphones, PhoneCall, Search, Store, UserRound, type LucideIcon } from "lucide-react";
import { TelecallerShell } from "@/components/telecaller/telecaller-shell";
import { ProfileSettings, ServiceReports } from "@/components/telecaller/telecaller-extras";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

const STATUSES = ["Assigned", "Call Pending", "Contacted", "Customer Unreachable", "Documents Required", "Follow-up Scheduled", "Ready for Processing", "Completed", "Cancelled"] as const;
type Status = (typeof STATUSES)[number];
const OUTCOMES = ["Connected", "Not Connected"] as const;
type CallOutcome = (typeof OUTCOMES)[number];
const DISPOSITIONS: Record<CallOutcome, readonly string[]> = {
  Connected: ["Information Confirmed", "Documents Required", "Callback Requested", "Ready for Processing", "Service Completed", "Customer Not Interested"],
  "Not Connected": ["No Answer", "Busy", "Switched Off", "Invalid Number", "Call Later"],
};
const DISPOSITION_STATUS: Record<string, Status> = {
  "Information Confirmed": "Contacted", "Documents Required": "Documents Required", "Callback Requested": "Follow-up Scheduled",
  "Ready for Processing": "Ready for Processing", "Service Completed": "Completed", "Customer Not Interested": "Cancelled",
  "No Answer": "Customer Unreachable", Busy: "Customer Unreachable", "Switched Off": "Customer Unreachable",
  "Invalid Number": "Customer Unreachable", "Call Later": "Follow-up Scheduled",
};
type Application = { id: string; retailer: string; retailerId: string; customer: string; phone: string; service: string; submitted: string; assigned: string; status: Status; priority: "High" | "Medium" | "Low"; nextAction: string; documents: string; notes: string; extraNotes: string; recordingLink: string; callOutcome?: CallOutcome; disposition?: string };

const INITIAL_APPLICATIONS: Application[] = [
  { id: "GST-240614-184", retailer: "Sri Balaji Digital", retailerId: "RT-10482", customer: "Rakesh Kumar", phone: "+91 98451 27420", service: "GST Registration", submitted: "14 Jun, 9:12 AM", assigned: "Today, 9:30 AM", status: "Call Pending", priority: "High", nextAction: "Call before 11:30 AM", documents: "PAN, Aadhaar, address proof", notes: "Retailer requested a Hindi callback." },
  { id: "PAN-240614-173", retailer: "Sana Services", retailerId: "RT-10715", customer: "Meena Devi", phone: "+91 80732 64019", service: "PAN Card", submitted: "14 Jun, 8:46 AM", assigned: "Today, 9:15 AM", status: "Documents Required", priority: "High", nextAction: "Today, 12:15 PM", documents: "Photo and signature pending", notes: "Aadhaar copy received." },
  { id: "UDY-240613-902", retailer: "Noor Online Point", retailerId: "RT-09281", customer: "Noor Traders", phone: "+91 99807 22140", service: "Udyam Registration", submitted: "13 Jun, 4:20 PM", assigned: "Yesterday, 5:05 PM", status: "Follow-up Scheduled", priority: "Medium", nextAction: "Today, 2:00 PM", documents: "All documents received", notes: "Confirm business activity before processing." },
  { id: "FSS-240613-876", retailer: "Akash CSC Center", retailerId: "RT-11204", customer: "Akash Foods", phone: "+91 90192 33740", service: "FSSAI Registration", submitted: "13 Jun, 2:10 PM", assigned: "Yesterday, 3:00 PM", status: "Customer Unreachable", priority: "Medium", nextAction: "Retry today, 3:30 PM", documents: "Premises photo pending", notes: "Two call attempts recorded." },
  { id: "PAN-240613-841", retailer: "Kaveri Enterprises", retailerId: "RT-08453", customer: "Divya Nair", phone: "+91 77609 55118", service: "PAN Card", submitted: "13 Jun, 11:35 AM", assigned: "Yesterday, 12:00 PM", status: "Ready for Processing", priority: "Low", nextAction: "Send to operations", documents: "Verified", notes: "Customer details confirmed." },
  { id: "GST-240612-744", retailer: "Metro Digital Seva", retailerId: "RT-07642", customer: "Sana Traders", phone: "+91 99008 11874", service: "GST Registration", submitted: "12 Jun, 3:48 PM", assigned: "12 Jun, 4:10 PM", status: "Completed", priority: "Low", nextAction: "Completed", documents: "Verified", notes: "Application successfully completed." },
];

const tone: Record<Status, string> = { Assigned: "bg-hr-soft text-hr", "Call Pending": "bg-saffron/10 text-saffron", Contacted: "bg-hr-soft text-hr", "Customer Unreachable": "bg-destructive/10 text-destructive", "Documents Required": "bg-chart-5/10 text-chart-5", "Follow-up Scheduled": "bg-saffron/10 text-saffron", "Ready for Processing": "bg-india-green/10 text-india-green", Completed: "bg-india-green/10 text-india-green", Cancelled: "bg-muted text-muted-foreground" };
const SUMMARY_CARDS: Array<[string, number, LucideIcon]> = [["Assigned", 5, ClipboardCheck], ["Call due", 3, PhoneCall], ["Follow-ups", 2, AlarmClock], ["Ready", 1, CheckCircle2]];
const KPI_CARDS: Array<[string, string, number, LucideIcon]> = [["Calls completed", "18 / 25", 72, Headphones], ["Customers reached", "13 / 18", 72, UserRound], ["Follow-ups due", "2", 40, CalendarClock], ["Ready for processing", "1", 20, CheckCircle2]];

export function ServiceApplicationWorkspace() {
  const [applications, setApplications] = useState(INITIAL_APPLICATIONS);
  const [activeSection, setActiveSection] = useState("command");
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("All statuses");
  const [selected, setSelected] = useState<Application | null>(null);
  const [draftStatus, setDraftStatus] = useState<Status>("Contacted");
  const [callOutcome, setCallOutcome] = useState<CallOutcome | "">("");
  const [disposition, setDisposition] = useState("");
  const [notes, setNotes] = useState("");
  const [nextAction, setNextAction] = useState("");
  const filtered = useMemo(() => applications.filter((item) => {
    const text = `${item.id} ${item.retailer} ${item.customer} ${item.phone} ${item.service}`.toLowerCase();
    const queueMatch = activeSection !== "calls" || ["Assigned", "Call Pending", "Customer Unreachable"].includes(item.status);
    const followupMatch = activeSection !== "followups" || ["Documents Required", "Follow-up Scheduled"].includes(item.status);
    return text.includes(query.toLowerCase()) && queueMatch && followupMatch && (statusFilter === "All statuses" || item.status === statusFilter);
  }), [activeSection, applications, query, statusFilter]);
  const openWork = (item: Application) => { setSelected(item); setDraftStatus(item.status === "Assigned" || item.status === "Call Pending" ? "Contacted" : item.status); setCallOutcome(item.callOutcome ?? ""); setDisposition(item.disposition ?? ""); setNotes(item.notes); setNextAction(item.nextAction); };
  const startCall = (item: Application) => { openWork(item); toast.success(`Calling ${item.customer}`, { description: `${item.phone} · ${item.service}` }); };
  const selectOutcome = (value: CallOutcome) => { setCallOutcome(value); setDisposition(""); };
  const selectDisposition = (value: string) => { setDisposition(value); setDraftStatus(DISPOSITION_STATUS[value] ?? "Contacted"); };
  const saveOutcome = () => {
    if (!selected) return;
    if (!callOutcome || !disposition) { toast.error("Select a call outcome and disposition"); return; }
    setApplications((current) => current.map((item) => item.id === selected.id ? { ...item, status: draftStatus, callOutcome, disposition, notes: notes.trim(), nextAction: nextAction.trim() || "No next action" } : item));
    toast.success("Call disposition saved", { description: `${selected.id} moved to ${draftStatus}.` });
    setSelected(null);
  };

  if (activeSection === "profile" || activeSection === "settings") return <TelecallerShell activeSection={activeSection} onSectionChange={setActiveSection}><div className="mx-auto max-w-[1500px]"><ProfileSettings mode={activeSection} /></div></TelecallerShell>;
  const pending = applications.filter((item) => !["Completed", "Cancelled"].includes(item.status));
  const reportLeads = applications.map((item) => ({ ...item, name: item.customer, source: item.retailer, owner: "Arjun K." }));
  return <TelecallerShell activeSection={activeSection} onSectionChange={setActiveSection}><div className="mx-auto max-w-[1600px] space-y-5">
    {activeSection === "command" && <><section className="rounded-3xl bg-navy p-6 text-hr-foreground shadow-elev lg:p-8"><div className="flex flex-col gap-7 xl:flex-row xl:items-center xl:justify-between"><div><Badge className="border border-hr-foreground/15 bg-hr-foreground/10 text-hr-foreground"><Store className="mr-1 h-3 w-3" /> Retailer service desk</Badge><h1 className="mt-4 font-display text-3xl font-extrabold sm:text-4xl">Assigned Service Applications</h1><p className="mt-2 max-w-2xl text-sm text-hr-foreground/65">Call customers for applications submitted through retailer portals, verify requirements, collect missing information, and update each service outcome.</p><Button className="mt-5 bg-hr text-hr-foreground hover:bg-hr/90" onClick={() => setActiveSection("calls")}><PhoneCall /> Start call queue</Button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:w-[600px]">{SUMMARY_CARDS.map(([label, fallbackValue, Icon]) => <div key={label} className="rounded-2xl border border-hr-foreground/10 bg-hr-foreground/10 p-4"><Icon className="h-4 w-4 text-hr" /><p className="mt-3 text-2xl font-extrabold">{label === "Assigned" ? pending.length : fallbackValue}</p><p className="text-[10px] uppercase tracking-wider text-hr-foreground/55">{label}</p></div>)}</div></div></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{KPI_CARDS.map(([label, value, progress, Icon]) => <div key={label} className="rounded-2xl border border-border bg-card p-4 shadow-soft"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-hr-soft text-hr"><Icon className="h-5 w-5" /></span></div><Progress value={progress} className="mt-4 [&>div]:bg-hr" /></div>)}</section></>}
    {activeSection === "reports" ? <ServiceReports leads={reportLeads} /> : activeSection === "performance" ? <section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><p className="text-[10px] font-bold uppercase tracking-wider text-hr">My work today</p><h2 className="font-display text-xl font-extrabold">Telecaller performance</h2><div className="mt-6 grid gap-4 sm:grid-cols-4">{[["Assigned", "24"], ["Calls", "18"], ["Resolved", "11"], ["Avg. handling", "4m 12s"]].map(([label, value]) => <div key={label} className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>)}</div></section> : activeSection === "script" ? <section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><p className="text-[10px] font-bold uppercase tracking-wider text-hr">Approved service call</p><h2 className="font-display text-xl font-extrabold">Customer verification script</h2><blockquote className="mt-5 border-l-4 border-hr bg-hr-soft p-5 font-semibold leading-7">“Hello, I am calling from BharatOne regarding your service application submitted through a BharatOne retailer. I will help verify the details and explain any pending requirements. Is this a convenient time to speak?”</blockquote></section> : <ApplicationTable activeSection={activeSection} filtered={filtered} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} openWork={activeSection === "calls" ? startCall : openWork} />}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{selected?.service} · {selected?.id}</DialogTitle><DialogDescription>Record the call outcome and disposition. The service application status updates automatically.</DialogDescription></DialogHeader>{selected && <div className="space-y-5"><div className="grid gap-3 rounded-xl bg-muted p-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase text-muted-foreground">Customer</p><p className="font-bold">{selected.customer}</p><p className="text-xs text-muted-foreground">{selected.phone}</p></div><div><p className="text-[10px] font-bold uppercase text-muted-foreground">Submitted by retailer</p><p className="font-bold">{selected.retailer}</p><p className="text-xs text-muted-foreground">{selected.retailerId} · {selected.submitted}</p></div></div><div className="rounded-xl border border-border p-4"><p className="flex items-center gap-2 text-sm font-bold"><FileText className="h-4 w-4 text-hr" /> Document requirement</p><p className="mt-1 text-xs text-muted-foreground">{selected.documents}</p></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Call outcome</Label><Select value={callOutcome} onValueChange={(value) => selectOutcome(value as CallOutcome)}><SelectTrigger className="mt-2"><SelectValue placeholder="Select outcome" /></SelectTrigger><SelectContent>{OUTCOMES.map((outcome) => <SelectItem key={outcome} value={outcome}>{outcome}</SelectItem>)}</SelectContent></Select></div><div><Label>Disposition</Label><Select value={disposition} onValueChange={selectDisposition} disabled={!callOutcome}><SelectTrigger className="mt-2"><SelectValue placeholder="Select disposition" /></SelectTrigger><SelectContent>{callOutcome && DISPOSITIONS[callOutcome].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Application status</Label><div className="mt-2 flex h-10 items-center rounded-md border border-border bg-muted px-3"><Badge variant="outline" className={tone[draftStatus]}>{draftStatus}</Badge></div><p className="mt-1 text-[11px] text-muted-foreground">Set automatically from the disposition.</p></div><div><Label htmlFor="next-action">Next action or follow-up</Label><Input id="next-action" className="mt-2" value={nextAction} onChange={(event) => setNextAction(event.target.value)} /></div></div><div><Label htmlFor="call-notes">Call notes</Label><Textarea id="call-notes" className="mt-2 min-h-28" value={notes} onChange={(event) => setNotes(event.target.value)} /></div></div>}<DialogFooter><Button variant="outline" onClick={() => selected && toast.success("Calling customer", { description: selected.phone })}><PhoneCall /> Start call</Button><Button onClick={saveOutcome}><ClipboardCheck /> Save disposition</Button></DialogFooter></DialogContent></Dialog>
  </div></TelecallerShell>;
}

function ApplicationTable({ activeSection, filtered, query, setQuery, statusFilter, setStatusFilter, openWork }: { activeSection: string; filtered: Application[]; query: string; setQuery: (value: string) => void; statusFilter: string; setStatusFilter: (value: string) => void; openWork: (item: Application) => void }) {
  return <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft"><div className="flex flex-col gap-3 border-b border-border p-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-hr">Admin assigned workload</p><h2 className="font-display text-xl font-extrabold">{activeSection === "calls" ? "My assigned call queue" : activeSection === "followups" ? "Follow-up queue" : "Retailer service applications"}</h2><p className="text-xs text-muted-foreground">Only applications assigned to you are shown here.</p></div><div className="flex flex-col gap-2 sm:flex-row"><div className="flex h-9 items-center gap-2 rounded-md border border-input bg-background px-3"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-60 bg-transparent text-sm outline-none" placeholder="Search application or customer" /></div><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="All statuses">All statuses</SelectItem>{STATUSES.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-sm"><thead className="bg-muted/50"><tr>{["Application", "Retailer", "Customer", "Status / disposition", "Next action", "Assigned", "Action"].map((header) => <th key={header} className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((item) => <tr key={item.id} className="hover:bg-muted/30"><td className="px-4 py-3"><p className="font-bold">{item.service}</p><p className="text-[11px] text-muted-foreground">{item.id}</p></td><td className="px-4 py-3"><p className="font-semibold">{item.retailer}</p><p className="text-[11px] text-muted-foreground">{item.retailerId}</p></td><td className="px-4 py-3"><p className="font-semibold">{item.customer}</p><p className="text-[11px] text-muted-foreground">{item.phone}</p></td><td className="px-4 py-3"><Badge variant="outline" className={tone[item.status]}>{item.status}</Badge>{item.disposition && <p className="mt-1 text-[11px] text-muted-foreground">{item.callOutcome} · {item.disposition}</p>}</td><td className="px-4 py-3 text-xs"><Clock3 className="mr-1 inline h-3.5 w-3.5 text-hr" />{item.nextAction}</td><td className="px-4 py-3 text-xs text-muted-foreground">{item.assigned}</td><td className="px-4 py-3"><Button size="sm" onClick={() => openWork(item)}><PhoneCall /> {activeSection === "calls" ? "Start call" : "Call & update"}</Button></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">No assigned applications match this queue.</div>}</div></section>;
}