/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VideoKycRouteImport } from './routes/video-kyc'
import { Route as TroLoginRouteImport } from './routes/tro-login'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TrackApplicationRouteImport } from './routes/track-application'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TelecallerLoginRouteImport } from './routes/telecaller-login'
import { Route as TelecallerRouteImport } from './routes/telecaller'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as QcLoginRouteImport } from './routes/qc-login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PanRouteImport } from './routes/pan'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewServiceRequestRouteImport } from './routes/new-service-request'
import { Route as MoneyTransferRouteImport } from './routes/money-transfer'
import { Route as MasterDistributorLoginRouteImport } from './routes/master-distributor-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HrLoginRouteImport } from './routes/hr-login'
import { Route as GstRouteImport } from './routes/gst'
import { Route as GovServicesRouteImport } from './routes/gov-services'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DroLoginRouteImport } from './routes/dro-login'
import { Route as DistributorLoginRouteImport } from './routes/distributor-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BusinessRegRouteImport } from './routes/business-reg'
import { Route as BdeLoginRouteImport } from './routes/bde-login'
import { Route as BbpsRouteImport } from './routes/bbps'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AepsActivationRouteImport } from './routes/aeps-activation'
import { Route as AepsRouteImport } from './routes/aeps'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AccountantLoginRouteImport } from './routes/accountant-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TroSupportRouteImport } from './routes/tro.support'
import { Route as TroServicesRouteImport } from './routes/tro.services'
import { Route as TroRetailersRouteImport } from './routes/tro.retailers'
import { Route as TroProfileRouteImport } from './routes/tro.profile'
import { Route as TroNotificationsRouteImport } from './routes/tro.notifications'
import { Route as TroFeedbackDeskRouteImport } from './routes/tro.feedback-desk'
import { Route as TroFeedbackRouteImport } from './routes/tro.feedback'
import { Route as TroDashboardRouteImport } from './routes/tro.dashboard'
import { Route as TroCatalogRouteImport } from './routes/tro.catalog'
import { Route as TroAttendanceRouteImport } from './routes/tro.attendance'
import { Route as QcSupportRouteImport } from './routes/qc.support'
import { Route as QcSettingsRouteImport } from './routes/qc.settings'
import { Route as QcReviewersRouteImport } from './routes/qc.reviewers'
import { Route as QcReportsRouteImport } from './routes/qc.reports'
import { Route as QcProfileRouteImport } from './routes/qc.profile'
import { Route as QcKycQueueRouteImport } from './routes/qc.kyc-queue'
import { Route as QcFlaggedRouteImport } from './routes/qc.flagged'
import { Route as QcFeedbackRouteImport } from './routes/qc.feedback'
import { Route as QcDocumentSearchRouteImport } from './routes/qc.document-search'
import { Route as QcDashboardRouteImport } from './routes/qc.dashboard'
import { Route as QcChangePasswordRouteImport } from './routes/qc.change-password'
import { Route as QcApprovedRouteImport } from './routes/qc.approved'
import { Route as HrTrainingRouteImport } from './routes/hr.training'
import { Route as HrSupportRouteImport } from './routes/hr.support'
import { Route as HrSettingsRouteImport } from './routes/hr.settings'
import { Route as HrReportsRouteImport } from './routes/hr.reports'
import { Route as HrRecruitmentRouteImport } from './routes/hr.recruitment'
import { Route as HrProfileRouteImport } from './routes/hr.profile'
import { Route as HrPerformanceRouteImport } from './routes/hr.performance'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrOnboardingRouteImport } from './routes/hr.onboarding'
import { Route as HrLeaveRouteImport } from './routes/hr.leave'
import { Route as HrFeedbackRouteImport } from './routes/hr.feedback'
import { Route as HrEmployeesRouteImport } from './routes/hr.employees'
import { Route as HrDashboardRouteImport } from './routes/hr.dashboard'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as DroSupportRouteImport } from './routes/dro.support'
import { Route as DroServicesRouteImport } from './routes/dro.services'
import { Route as DroRetailersRouteImport } from './routes/dro.retailers'
import { Route as DroProfileRouteImport } from './routes/dro.profile'
import { Route as DroNotificationsRouteImport } from './routes/dro.notifications'
import { Route as DroFeedbackDeskRouteImport } from './routes/dro.feedback-desk'
import { Route as DroFeedbackRouteImport } from './routes/dro.feedback'
import { Route as DroDashboardRouteImport } from './routes/dro.dashboard'
import { Route as DroCatalogRouteImport } from './routes/dro.catalog'
import { Route as DroAttendanceRouteImport } from './routes/dro.attendance'
import { Route as DistributorSupportRouteImport } from './routes/distributor.support'
import { Route as DistributorSettingsRouteImport } from './routes/distributor.settings'
import { Route as DistributorServicesRouteImport } from './routes/distributor.services'
import { Route as DistributorSalesDashboardRouteImport } from './routes/distributor.sales-dashboard'
import { Route as DistributorRetailersRouteImport } from './routes/distributor.retailers'
import { Route as DistributorReportsRouteImport } from './routes/distributor.reports'
import { Route as DistributorOfficersRouteImport } from './routes/distributor.officers'
import { Route as DistributorNetworkRouteImport } from './routes/distributor.network'
import { Route as DistributorFeedbackRouteImport } from './routes/distributor.feedback'
import { Route as DistributorDashboardRouteImport } from './routes/distributor.dashboard'
import { Route as DistributorCommissionsRouteImport } from './routes/distributor.commissions'
import { Route as BdeSupportRouteImport } from './routes/bde.support'
import { Route as BdeSettingsRouteImport } from './routes/bde.settings'
import { Route as BdeReportsRouteImport } from './routes/bde.reports'
import { Route as BdeProfileRouteImport } from './routes/bde.profile'
import { Route as BdePerformanceRouteImport } from './routes/bde.performance'
import { Route as BdeOpportunitiesRouteImport } from './routes/bde.opportunities'
import { Route as BdeNetworkRouteImport } from './routes/bde.network'
import { Route as BdeMerchantsRouteImport } from './routes/bde.merchants'
import { Route as BdeLeadsRouteImport } from './routes/bde.leads'
import { Route as BdeFeedbackRouteImport } from './routes/bde.feedback'
import { Route as BdeDashboardRouteImport } from './routes/bde.dashboard'
import { Route as AccountantWithdrawalsRouteImport } from './routes/accountant.withdrawals'
import { Route as AccountantWalletRequestsRouteImport } from './routes/accountant.wallet-requests'
import { Route as AccountantSupportRouteImport } from './routes/accountant.support'
import { Route as AccountantSettingsRouteImport } from './routes/accountant.settings'
import { Route as AccountantServicesRouteImport } from './routes/accountant.services'
import { Route as AccountantRegistrationsRouteImport } from './routes/accountant.registrations'
import { Route as AccountantProfileRouteImport } from './routes/accountant.profile'
import { Route as AccountantMainRechargeRouteImport } from './routes/accountant.main-recharge'
import { Route as AccountantLedgerRouteImport } from './routes/accountant.ledger'
import { Route as AccountantFeedbackRouteImport } from './routes/accountant.feedback'
import { Route as AccountantDashboardRouteImport } from './routes/accountant.dashboard'
import { Route as AccountantChangePasswordRouteImport } from './routes/accountant.change-password'
import { Route as DistributorRetailersIndexRouteImport } from './routes/distributor.retailers.index'
import { Route as TroRetailersIdRouteImport } from './routes/tro.retailers.$id'
import { Route as QcKycReviewIdRouteImport } from './routes/qc.kyc-review.$id'
import { Route as DroRetailersIdRouteImport } from './routes/dro.retailers.$id'
import { Route as DistributorServicesKeyRouteImport } from './routes/distributor.services.$key'
import { Route as DistributorRetailersIdRouteImport } from './routes/distributor.retailers.$id'
import { Route as DistributorOfficersIdRouteImport } from './routes/distributor.officers.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoKycRoute = VideoKycRouteImport.update({
  id: '/video-kyc',
  path: '/video-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const TroLoginRoute = TroLoginRouteImport.update({
  id: '/tro-login',
  path: '/tro-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackApplicationRoute = TrackApplicationRouteImport.update({
  id: '/track-application',
  path: '/track-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TelecallerLoginRoute = TelecallerLoginRouteImport.update({
  id: '/telecaller-login',
  path: '/telecaller-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TelecallerRoute = TelecallerRouteImport.update({
  id: '/telecaller',
  path: '/telecaller',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const QcLoginRoute = QcLoginRouteImport.update({
  id: '/qc-login',
  path: '/qc-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PanRoute = PanRouteImport.update({
  id: '/pan',
  path: '/pan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewServiceRequestRoute = NewServiceRequestRouteImport.update({
  id: '/new-service-request',
  path: '/new-service-request',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyTransferRoute = MoneyTransferRouteImport.update({
  id: '/money-transfer',
  path: '/money-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDistributorLoginRoute = MasterDistributorLoginRouteImport.update({
  id: '/master-distributor-login',
  path: '/master-distributor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLoginRoute = HrLoginRouteImport.update({
  id: '/hr-login',
  path: '/hr-login',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const GovServicesRoute = GovServicesRouteImport.update({
  id: '/gov-services',
  path: '/gov-services',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DroLoginRoute = DroLoginRouteImport.update({
  id: '/dro-login',
  path: '/dro-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorLoginRoute = DistributorLoginRouteImport.update({
  id: '/distributor-login',
  path: '/distributor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegRoute = BusinessRegRouteImport.update({
  id: '/business-reg',
  path: '/business-reg',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeLoginRoute = BdeLoginRouteImport.update({
  id: '/bde-login',
  path: '/bde-login',
  getParentRoute: () => rootRouteImport,
} as any)
const BbpsRoute = BbpsRouteImport.update({
  id: '/bbps',
  path: '/bbps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AepsActivationRoute = AepsActivationRouteImport.update({
  id: '/aeps-activation',
  path: '/aeps-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AepsRoute = AepsRouteImport.update({
  id: '/aeps',
  path: '/aeps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantLoginRoute = AccountantLoginRouteImport.update({
  id: '/accountant-login',
  path: '/accountant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroSupportRoute = TroSupportRouteImport.update({
  id: '/tro/support',
  path: '/tro/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TroServicesRoute = TroServicesRouteImport.update({
  id: '/tro/services',
  path: '/tro/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TroRetailersRoute = TroRetailersRouteImport.update({
  id: '/tro/retailers',
  path: '/tro/retailers',
  getParentRoute: () => rootRouteImport,
} as any)
const TroProfileRoute = TroProfileRouteImport.update({
  id: '/tro/profile',
  path: '/tro/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TroNotificationsRoute = TroNotificationsRouteImport.update({
  id: '/tro/notifications',
  path: '/tro/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TroFeedbackDeskRoute = TroFeedbackDeskRouteImport.update({
  id: '/tro/feedback-desk',
  path: '/tro/feedback-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TroFeedbackRoute = TroFeedbackRouteImport.update({
  id: '/tro/feedback',
  path: '/tro/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const TroDashboardRoute = TroDashboardRouteImport.update({
  id: '/tro/dashboard',
  path: '/tro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TroCatalogRoute = TroCatalogRouteImport.update({
  id: '/tro/catalog',
  path: '/tro/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TroAttendanceRoute = TroAttendanceRouteImport.update({
  id: '/tro/attendance',
  path: '/tro/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const QcSupportRoute = QcSupportRouteImport.update({
  id: '/qc/support',
  path: '/qc/support',
  getParentRoute: () => rootRouteImport,
} as any)
const QcSettingsRoute = QcSettingsRouteImport.update({
  id: '/qc/settings',
  path: '/qc/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QcReviewersRoute = QcReviewersRouteImport.update({
  id: '/qc/reviewers',
  path: '/qc/reviewers',
  getParentRoute: () => rootRouteImport,
} as any)
const QcReportsRoute = QcReportsRouteImport.update({
  id: '/qc/reports',
  path: '/qc/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QcProfileRoute = QcProfileRouteImport.update({
  id: '/qc/profile',
  path: '/qc/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QcKycQueueRoute = QcKycQueueRouteImport.update({
  id: '/qc/kyc-queue',
  path: '/qc/kyc-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const QcFlaggedRoute = QcFlaggedRouteImport.update({
  id: '/qc/flagged',
  path: '/qc/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const QcFeedbackRoute = QcFeedbackRouteImport.update({
  id: '/qc/feedback',
  path: '/qc/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const QcDocumentSearchRoute = QcDocumentSearchRouteImport.update({
  id: '/qc/document-search',
  path: '/qc/document-search',
  getParentRoute: () => rootRouteImport,
} as any)
const QcDashboardRoute = QcDashboardRouteImport.update({
  id: '/qc/dashboard',
  path: '/qc/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QcChangePasswordRoute = QcChangePasswordRouteImport.update({
  id: '/qc/change-password',
  path: '/qc/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QcApprovedRoute = QcApprovedRouteImport.update({
  id: '/qc/approved',
  path: '/qc/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const HrTrainingRoute = HrTrainingRouteImport.update({
  id: '/hr/training',
  path: '/hr/training',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSupportRoute = HrSupportRouteImport.update({
  id: '/hr/support',
  path: '/hr/support',
  getParentRoute: () => rootRouteImport,
} as any)
const HrSettingsRoute = HrSettingsRouteImport.update({
  id: '/hr/settings',
  path: '/hr/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HrReportsRoute = HrReportsRouteImport.update({
  id: '/hr/reports',
  path: '/hr/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRecruitmentRoute = HrRecruitmentRouteImport.update({
  id: '/hr/recruitment',
  path: '/hr/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const HrProfileRoute = HrProfileRouteImport.update({
  id: '/hr/profile',
  path: '/hr/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPerformanceRoute = HrPerformanceRouteImport.update({
  id: '/hr/performance',
  path: '/hr/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrOnboardingRoute = HrOnboardingRouteImport.update({
  id: '/hr/onboarding',
  path: '/hr/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveRoute = HrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrFeedbackRoute = HrFeedbackRouteImport.update({
  id: '/hr/feedback',
  path: '/hr/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/hr/dashboard',
  path: '/hr/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DroSupportRoute = DroSupportRouteImport.update({
  id: '/dro/support',
  path: '/dro/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DroServicesRoute = DroServicesRouteImport.update({
  id: '/dro/services',
  path: '/dro/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DroRetailersRoute = DroRetailersRouteImport.update({
  id: '/dro/retailers',
  path: '/dro/retailers',
  getParentRoute: () => rootRouteImport,
} as any)
const DroProfileRoute = DroProfileRouteImport.update({
  id: '/dro/profile',
  path: '/dro/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DroNotificationsRoute = DroNotificationsRouteImport.update({
  id: '/dro/notifications',
  path: '/dro/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DroFeedbackDeskRoute = DroFeedbackDeskRouteImport.update({
  id: '/dro/feedback-desk',
  path: '/dro/feedback-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DroFeedbackRoute = DroFeedbackRouteImport.update({
  id: '/dro/feedback',
  path: '/dro/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DroDashboardRoute = DroDashboardRouteImport.update({
  id: '/dro/dashboard',
  path: '/dro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DroCatalogRoute = DroCatalogRouteImport.update({
  id: '/dro/catalog',
  path: '/dro/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DroAttendanceRoute = DroAttendanceRouteImport.update({
  id: '/dro/attendance',
  path: '/dro/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorSupportRoute = DistributorSupportRouteImport.update({
  id: '/distributor/support',
  path: '/distributor/support',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorSettingsRoute = DistributorSettingsRouteImport.update({
  id: '/distributor/settings',
  path: '/distributor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorServicesRoute = DistributorServicesRouteImport.update({
  id: '/distributor/services',
  path: '/distributor/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorSalesDashboardRoute =
  DistributorSalesDashboardRouteImport.update({
    id: '/distributor/sales-dashboard',
    path: '/distributor/sales-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistributorRetailersRoute = DistributorRetailersRouteImport.update({
  id: '/distributor/retailers',
  path: '/distributor/retailers',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorReportsRoute = DistributorReportsRouteImport.update({
  id: '/distributor/reports',
  path: '/distributor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorOfficersRoute = DistributorOfficersRouteImport.update({
  id: '/distributor/officers',
  path: '/distributor/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorNetworkRoute = DistributorNetworkRouteImport.update({
  id: '/distributor/network',
  path: '/distributor/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorFeedbackRoute = DistributorFeedbackRouteImport.update({
  id: '/distributor/feedback',
  path: '/distributor/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorDashboardRoute = DistributorDashboardRouteImport.update({
  id: '/distributor/dashboard',
  path: '/distributor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorCommissionsRoute = DistributorCommissionsRouteImport.update({
  id: '/distributor/commissions',
  path: '/distributor/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeSupportRoute = BdeSupportRouteImport.update({
  id: '/bde/support',
  path: '/bde/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeSettingsRoute = BdeSettingsRouteImport.update({
  id: '/bde/settings',
  path: '/bde/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeReportsRoute = BdeReportsRouteImport.update({
  id: '/bde/reports',
  path: '/bde/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeProfileRoute = BdeProfileRouteImport.update({
  id: '/bde/profile',
  path: '/bde/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BdePerformanceRoute = BdePerformanceRouteImport.update({
  id: '/bde/performance',
  path: '/bde/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeOpportunitiesRoute = BdeOpportunitiesRouteImport.update({
  id: '/bde/opportunities',
  path: '/bde/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeNetworkRoute = BdeNetworkRouteImport.update({
  id: '/bde/network',
  path: '/bde/network',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeMerchantsRoute = BdeMerchantsRouteImport.update({
  id: '/bde/merchants',
  path: '/bde/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeLeadsRoute = BdeLeadsRouteImport.update({
  id: '/bde/leads',
  path: '/bde/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeFeedbackRoute = BdeFeedbackRouteImport.update({
  id: '/bde/feedback',
  path: '/bde/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeDashboardRoute = BdeDashboardRouteImport.update({
  id: '/bde/dashboard',
  path: '/bde/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantWithdrawalsRoute = AccountantWithdrawalsRouteImport.update({
  id: '/accountant/withdrawals',
  path: '/accountant/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantWalletRequestsRoute =
  AccountantWalletRequestsRouteImport.update({
    id: '/accountant/wallet-requests',
    path: '/accountant/wallet-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountantSupportRoute = AccountantSupportRouteImport.update({
  id: '/accountant/support',
  path: '/accountant/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantSettingsRoute = AccountantSettingsRouteImport.update({
  id: '/accountant/settings',
  path: '/accountant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantServicesRoute = AccountantServicesRouteImport.update({
  id: '/accountant/services',
  path: '/accountant/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRegistrationsRoute = AccountantRegistrationsRouteImport.update({
  id: '/accountant/registrations',
  path: '/accountant/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantProfileRoute = AccountantProfileRouteImport.update({
  id: '/accountant/profile',
  path: '/accountant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantMainRechargeRoute = AccountantMainRechargeRouteImport.update({
  id: '/accountant/main-recharge',
  path: '/accountant/main-recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantLedgerRoute = AccountantLedgerRouteImport.update({
  id: '/accountant/ledger',
  path: '/accountant/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantFeedbackRoute = AccountantFeedbackRouteImport.update({
  id: '/accountant/feedback',
  path: '/accountant/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantDashboardRoute = AccountantDashboardRouteImport.update({
  id: '/accountant/dashboard',
  path: '/accountant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantChangePasswordRoute =
  AccountantChangePasswordRouteImport.update({
    id: '/accountant/change-password',
    path: '/accountant/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistributorRetailersIndexRoute =
  DistributorRetailersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DistributorRetailersRoute,
  } as any)
const TroRetailersIdRoute = TroRetailersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TroRetailersRoute,
} as any)
const QcKycReviewIdRoute = QcKycReviewIdRouteImport.update({
  id: '/qc/kyc-review/$id',
  path: '/qc/kyc-review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DroRetailersIdRoute = DroRetailersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DroRetailersRoute,
} as any)
const DistributorServicesKeyRoute = DistributorServicesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => DistributorServicesRoute,
} as any)
const DistributorRetailersIdRoute = DistributorRetailersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistributorRetailersRoute,
} as any)
const DistributorOfficersIdRoute = DistributorOfficersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistributorOfficersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/bde-login': typeof BdeLoginRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/feedback': typeof FeedbackRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/hr-login': typeof HrLoginRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/telecaller': typeof TelecallerRoute
  '/telecaller-login': typeof TelecallerLoginRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/feedback': typeof AccountantFeedbackRoute
  '/accountant/ledger': typeof AccountantLedgerRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/support': typeof AccountantSupportRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/bde/dashboard': typeof BdeDashboardRoute
  '/bde/feedback': typeof BdeFeedbackRoute
  '/bde/leads': typeof BdeLeadsRoute
  '/bde/merchants': typeof BdeMerchantsRoute
  '/bde/network': typeof BdeNetworkRoute
  '/bde/opportunities': typeof BdeOpportunitiesRoute
  '/bde/performance': typeof BdePerformanceRoute
  '/bde/profile': typeof BdeProfileRoute
  '/bde/reports': typeof BdeReportsRoute
  '/bde/settings': typeof BdeSettingsRoute
  '/bde/support': typeof BdeSupportRoute
  '/distributor/commissions': typeof DistributorCommissionsRoute
  '/distributor/dashboard': typeof DistributorDashboardRoute
  '/distributor/feedback': typeof DistributorFeedbackRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/officers': typeof DistributorOfficersRouteWithChildren
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/retailers': typeof DistributorRetailersRouteWithChildren
  '/distributor/sales-dashboard': typeof DistributorSalesDashboardRoute
  '/distributor/services': typeof DistributorServicesRouteWithChildren
  '/distributor/settings': typeof DistributorSettingsRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/dro/attendance': typeof DroAttendanceRoute
  '/dro/catalog': typeof DroCatalogRoute
  '/dro/dashboard': typeof DroDashboardRoute
  '/dro/feedback': typeof DroFeedbackRoute
  '/dro/feedback-desk': typeof DroFeedbackDeskRoute
  '/dro/notifications': typeof DroNotificationsRoute
  '/dro/profile': typeof DroProfileRoute
  '/dro/retailers': typeof DroRetailersRouteWithChildren
  '/dro/services': typeof DroServicesRoute
  '/dro/support': typeof DroSupportRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/feedback': typeof HrFeedbackRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/profile': typeof HrProfileRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/hr/support': typeof HrSupportRoute
  '/hr/training': typeof HrTrainingRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/feedback': typeof QcFeedbackRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/support': typeof QcSupportRoute
  '/tro/attendance': typeof TroAttendanceRoute
  '/tro/catalog': typeof TroCatalogRoute
  '/tro/dashboard': typeof TroDashboardRoute
  '/tro/feedback': typeof TroFeedbackRoute
  '/tro/feedback-desk': typeof TroFeedbackDeskRoute
  '/tro/notifications': typeof TroNotificationsRoute
  '/tro/profile': typeof TroProfileRoute
  '/tro/retailers': typeof TroRetailersRouteWithChildren
  '/tro/services': typeof TroServicesRoute
  '/tro/support': typeof TroSupportRoute
  '/distributor/officers/$id': typeof DistributorOfficersIdRoute
  '/distributor/retailers/$id': typeof DistributorRetailersIdRoute
  '/distributor/services/$key': typeof DistributorServicesKeyRoute
  '/dro/retailers/$id': typeof DroRetailersIdRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
  '/tro/retailers/$id': typeof TroRetailersIdRoute
  '/distributor/retailers/': typeof DistributorRetailersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/bde-login': typeof BdeLoginRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/feedback': typeof FeedbackRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/hr-login': typeof HrLoginRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/telecaller': typeof TelecallerRoute
  '/telecaller-login': typeof TelecallerLoginRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/feedback': typeof AccountantFeedbackRoute
  '/accountant/ledger': typeof AccountantLedgerRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/support': typeof AccountantSupportRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/bde/dashboard': typeof BdeDashboardRoute
  '/bde/feedback': typeof BdeFeedbackRoute
  '/bde/leads': typeof BdeLeadsRoute
  '/bde/merchants': typeof BdeMerchantsRoute
  '/bde/network': typeof BdeNetworkRoute
  '/bde/opportunities': typeof BdeOpportunitiesRoute
  '/bde/performance': typeof BdePerformanceRoute
  '/bde/profile': typeof BdeProfileRoute
  '/bde/reports': typeof BdeReportsRoute
  '/bde/settings': typeof BdeSettingsRoute
  '/bde/support': typeof BdeSupportRoute
  '/distributor/commissions': typeof DistributorCommissionsRoute
  '/distributor/dashboard': typeof DistributorDashboardRoute
  '/distributor/feedback': typeof DistributorFeedbackRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/officers': typeof DistributorOfficersRouteWithChildren
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/sales-dashboard': typeof DistributorSalesDashboardRoute
  '/distributor/services': typeof DistributorServicesRouteWithChildren
  '/distributor/settings': typeof DistributorSettingsRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/dro/attendance': typeof DroAttendanceRoute
  '/dro/catalog': typeof DroCatalogRoute
  '/dro/dashboard': typeof DroDashboardRoute
  '/dro/feedback': typeof DroFeedbackRoute
  '/dro/feedback-desk': typeof DroFeedbackDeskRoute
  '/dro/notifications': typeof DroNotificationsRoute
  '/dro/profile': typeof DroProfileRoute
  '/dro/retailers': typeof DroRetailersRouteWithChildren
  '/dro/services': typeof DroServicesRoute
  '/dro/support': typeof DroSupportRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/feedback': typeof HrFeedbackRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/profile': typeof HrProfileRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/hr/support': typeof HrSupportRoute
  '/hr/training': typeof HrTrainingRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/feedback': typeof QcFeedbackRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/support': typeof QcSupportRoute
  '/tro/attendance': typeof TroAttendanceRoute
  '/tro/catalog': typeof TroCatalogRoute
  '/tro/dashboard': typeof TroDashboardRoute
  '/tro/feedback': typeof TroFeedbackRoute
  '/tro/feedback-desk': typeof TroFeedbackDeskRoute
  '/tro/notifications': typeof TroNotificationsRoute
  '/tro/profile': typeof TroProfileRoute
  '/tro/retailers': typeof TroRetailersRouteWithChildren
  '/tro/services': typeof TroServicesRoute
  '/tro/support': typeof TroSupportRoute
  '/distributor/officers/$id': typeof DistributorOfficersIdRoute
  '/distributor/retailers/$id': typeof DistributorRetailersIdRoute
  '/distributor/services/$key': typeof DistributorServicesKeyRoute
  '/dro/retailers/$id': typeof DroRetailersIdRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
  '/tro/retailers/$id': typeof TroRetailersIdRoute
  '/distributor/retailers': typeof DistributorRetailersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/bde-login': typeof BdeLoginRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/feedback': typeof FeedbackRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/hr-login': typeof HrLoginRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/telecaller': typeof TelecallerRoute
  '/telecaller-login': typeof TelecallerLoginRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/feedback': typeof AccountantFeedbackRoute
  '/accountant/ledger': typeof AccountantLedgerRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/support': typeof AccountantSupportRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/bde/dashboard': typeof BdeDashboardRoute
  '/bde/feedback': typeof BdeFeedbackRoute
  '/bde/leads': typeof BdeLeadsRoute
  '/bde/merchants': typeof BdeMerchantsRoute
  '/bde/network': typeof BdeNetworkRoute
  '/bde/opportunities': typeof BdeOpportunitiesRoute
  '/bde/performance': typeof BdePerformanceRoute
  '/bde/profile': typeof BdeProfileRoute
  '/bde/reports': typeof BdeReportsRoute
  '/bde/settings': typeof BdeSettingsRoute
  '/bde/support': typeof BdeSupportRoute
  '/distributor/commissions': typeof DistributorCommissionsRoute
  '/distributor/dashboard': typeof DistributorDashboardRoute
  '/distributor/feedback': typeof DistributorFeedbackRoute
  '/distributor/network': typeof DistributorNetworkRoute
  '/distributor/officers': typeof DistributorOfficersRouteWithChildren
  '/distributor/reports': typeof DistributorReportsRoute
  '/distributor/retailers': typeof DistributorRetailersRouteWithChildren
  '/distributor/sales-dashboard': typeof DistributorSalesDashboardRoute
  '/distributor/services': typeof DistributorServicesRouteWithChildren
  '/distributor/settings': typeof DistributorSettingsRoute
  '/distributor/support': typeof DistributorSupportRoute
  '/dro/attendance': typeof DroAttendanceRoute
  '/dro/catalog': typeof DroCatalogRoute
  '/dro/dashboard': typeof DroDashboardRoute
  '/dro/feedback': typeof DroFeedbackRoute
  '/dro/feedback-desk': typeof DroFeedbackDeskRoute
  '/dro/notifications': typeof DroNotificationsRoute
  '/dro/profile': typeof DroProfileRoute
  '/dro/retailers': typeof DroRetailersRouteWithChildren
  '/dro/services': typeof DroServicesRoute
  '/dro/support': typeof DroSupportRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/dashboard': typeof HrDashboardRoute
  '/hr/employees': typeof HrEmployeesRoute
  '/hr/feedback': typeof HrFeedbackRoute
  '/hr/leave': typeof HrLeaveRoute
  '/hr/onboarding': typeof HrOnboardingRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/profile': typeof HrProfileRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/reports': typeof HrReportsRoute
  '/hr/settings': typeof HrSettingsRoute
  '/hr/support': typeof HrSupportRoute
  '/hr/training': typeof HrTrainingRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/feedback': typeof QcFeedbackRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/support': typeof QcSupportRoute
  '/tro/attendance': typeof TroAttendanceRoute
  '/tro/catalog': typeof TroCatalogRoute
  '/tro/dashboard': typeof TroDashboardRoute
  '/tro/feedback': typeof TroFeedbackRoute
  '/tro/feedback-desk': typeof TroFeedbackDeskRoute
  '/tro/notifications': typeof TroNotificationsRoute
  '/tro/profile': typeof TroProfileRoute
  '/tro/retailers': typeof TroRetailersRouteWithChildren
  '/tro/services': typeof TroServicesRoute
  '/tro/support': typeof TroSupportRoute
  '/distributor/officers/$id': typeof DistributorOfficersIdRoute
  '/distributor/retailers/$id': typeof DistributorRetailersIdRoute
  '/distributor/services/$key': typeof DistributorServicesKeyRoute
  '/dro/retailers/$id': typeof DroRetailersIdRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
  '/tro/retailers/$id': typeof TroRetailersIdRoute
  '/distributor/retailers/': typeof DistributorRetailersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/bde-login'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/feedback'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/hr-login'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/telecaller'
    | '/telecaller-login'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/feedback'
    | '/accountant/ledger'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/support'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/bde/dashboard'
    | '/bde/feedback'
    | '/bde/leads'
    | '/bde/merchants'
    | '/bde/network'
    | '/bde/opportunities'
    | '/bde/performance'
    | '/bde/profile'
    | '/bde/reports'
    | '/bde/settings'
    | '/bde/support'
    | '/distributor/commissions'
    | '/distributor/dashboard'
    | '/distributor/feedback'
    | '/distributor/network'
    | '/distributor/officers'
    | '/distributor/reports'
    | '/distributor/retailers'
    | '/distributor/sales-dashboard'
    | '/distributor/services'
    | '/distributor/settings'
    | '/distributor/support'
    | '/dro/attendance'
    | '/dro/catalog'
    | '/dro/dashboard'
    | '/dro/feedback'
    | '/dro/feedback-desk'
    | '/dro/notifications'
    | '/dro/profile'
    | '/dro/retailers'
    | '/dro/services'
    | '/dro/support'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/employees'
    | '/hr/feedback'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/profile'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/hr/support'
    | '/hr/training'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/feedback'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/support'
    | '/tro/attendance'
    | '/tro/catalog'
    | '/tro/dashboard'
    | '/tro/feedback'
    | '/tro/feedback-desk'
    | '/tro/notifications'
    | '/tro/profile'
    | '/tro/retailers'
    | '/tro/services'
    | '/tro/support'
    | '/distributor/officers/$id'
    | '/distributor/retailers/$id'
    | '/distributor/services/$key'
    | '/dro/retailers/$id'
    | '/qc/kyc-review/$id'
    | '/tro/retailers/$id'
    | '/distributor/retailers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/bde-login'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/feedback'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/hr-login'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/telecaller'
    | '/telecaller-login'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/feedback'
    | '/accountant/ledger'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/support'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/bde/dashboard'
    | '/bde/feedback'
    | '/bde/leads'
    | '/bde/merchants'
    | '/bde/network'
    | '/bde/opportunities'
    | '/bde/performance'
    | '/bde/profile'
    | '/bde/reports'
    | '/bde/settings'
    | '/bde/support'
    | '/distributor/commissions'
    | '/distributor/dashboard'
    | '/distributor/feedback'
    | '/distributor/network'
    | '/distributor/officers'
    | '/distributor/reports'
    | '/distributor/sales-dashboard'
    | '/distributor/services'
    | '/distributor/settings'
    | '/distributor/support'
    | '/dro/attendance'
    | '/dro/catalog'
    | '/dro/dashboard'
    | '/dro/feedback'
    | '/dro/feedback-desk'
    | '/dro/notifications'
    | '/dro/profile'
    | '/dro/retailers'
    | '/dro/services'
    | '/dro/support'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/employees'
    | '/hr/feedback'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/profile'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/hr/support'
    | '/hr/training'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/feedback'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/support'
    | '/tro/attendance'
    | '/tro/catalog'
    | '/tro/dashboard'
    | '/tro/feedback'
    | '/tro/feedback-desk'
    | '/tro/notifications'
    | '/tro/profile'
    | '/tro/retailers'
    | '/tro/services'
    | '/tro/support'
    | '/distributor/officers/$id'
    | '/distributor/retailers/$id'
    | '/distributor/services/$key'
    | '/dro/retailers/$id'
    | '/qc/kyc-review/$id'
    | '/tro/retailers/$id'
    | '/distributor/retailers'
  id:
    | '__root__'
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/bde-login'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/feedback'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/hr-login'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/telecaller'
    | '/telecaller-login'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/feedback'
    | '/accountant/ledger'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/support'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/bde/dashboard'
    | '/bde/feedback'
    | '/bde/leads'
    | '/bde/merchants'
    | '/bde/network'
    | '/bde/opportunities'
    | '/bde/performance'
    | '/bde/profile'
    | '/bde/reports'
    | '/bde/settings'
    | '/bde/support'
    | '/distributor/commissions'
    | '/distributor/dashboard'
    | '/distributor/feedback'
    | '/distributor/network'
    | '/distributor/officers'
    | '/distributor/reports'
    | '/distributor/retailers'
    | '/distributor/sales-dashboard'
    | '/distributor/services'
    | '/distributor/settings'
    | '/distributor/support'
    | '/dro/attendance'
    | '/dro/catalog'
    | '/dro/dashboard'
    | '/dro/feedback'
    | '/dro/feedback-desk'
    | '/dro/notifications'
    | '/dro/profile'
    | '/dro/retailers'
    | '/dro/services'
    | '/dro/support'
    | '/hr/attendance'
    | '/hr/dashboard'
    | '/hr/employees'
    | '/hr/feedback'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/profile'
    | '/hr/recruitment'
    | '/hr/reports'
    | '/hr/settings'
    | '/hr/support'
    | '/hr/training'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/feedback'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/support'
    | '/tro/attendance'
    | '/tro/catalog'
    | '/tro/dashboard'
    | '/tro/feedback'
    | '/tro/feedback-desk'
    | '/tro/notifications'
    | '/tro/profile'
    | '/tro/retailers'
    | '/tro/services'
    | '/tro/support'
    | '/distributor/officers/$id'
    | '/distributor/retailers/$id'
    | '/distributor/services/$key'
    | '/dro/retailers/$id'
    | '/qc/kyc-review/$id'
    | '/tro/retailers/$id'
    | '/distributor/retailers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantLoginRoute: typeof AccountantLoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AepsRoute: typeof AepsRoute
  AepsActivationRoute: typeof AepsActivationRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BbpsRoute: typeof BbpsRoute
  BdeLoginRoute: typeof BdeLoginRoute
  BusinessRegRoute: typeof BusinessRegRoute
  DashboardRoute: typeof DashboardRoute
  DistributorLoginRoute: typeof DistributorLoginRoute
  DroLoginRoute: typeof DroLoginRoute
  FeedbackRoute: typeof FeedbackRoute
  GetStartedRoute: typeof GetStartedRoute
  GovServicesRoute: typeof GovServicesRoute
  GstRoute: typeof GstRoute
  HrLoginRoute: typeof HrLoginRoute
  LoginRoute: typeof LoginRoute
  MasterDistributorLoginRoute: typeof MasterDistributorLoginRoute
  MoneyTransferRoute: typeof MoneyTransferRoute
  NewServiceRequestRoute: typeof NewServiceRequestRoute
  NotificationsRoute: typeof NotificationsRoute
  PanRoute: typeof PanRoute
  PortalsRoute: typeof PortalsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QcLoginRoute: typeof QcLoginRoute
  RechargeRoute: typeof RechargeRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TelecallerRoute: typeof TelecallerRoute
  TelecallerLoginRoute: typeof TelecallerLoginRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackApplicationRoute: typeof TrackApplicationRoute
  TransactionsRoute: typeof TransactionsRoute
  TroLoginRoute: typeof TroLoginRoute
  VideoKycRoute: typeof VideoKycRoute
  WalletRoute: typeof WalletRoute
  AccountantChangePasswordRoute: typeof AccountantChangePasswordRoute
  AccountantDashboardRoute: typeof AccountantDashboardRoute
  AccountantFeedbackRoute: typeof AccountantFeedbackRoute
  AccountantLedgerRoute: typeof AccountantLedgerRoute
  AccountantMainRechargeRoute: typeof AccountantMainRechargeRoute
  AccountantProfileRoute: typeof AccountantProfileRoute
  AccountantRegistrationsRoute: typeof AccountantRegistrationsRoute
  AccountantServicesRoute: typeof AccountantServicesRoute
  AccountantSettingsRoute: typeof AccountantSettingsRoute
  AccountantSupportRoute: typeof AccountantSupportRoute
  AccountantWalletRequestsRoute: typeof AccountantWalletRequestsRoute
  AccountantWithdrawalsRoute: typeof AccountantWithdrawalsRoute
  BdeDashboardRoute: typeof BdeDashboardRoute
  BdeFeedbackRoute: typeof BdeFeedbackRoute
  BdeLeadsRoute: typeof BdeLeadsRoute
  BdeMerchantsRoute: typeof BdeMerchantsRoute
  BdeNetworkRoute: typeof BdeNetworkRoute
  BdeOpportunitiesRoute: typeof BdeOpportunitiesRoute
  BdePerformanceRoute: typeof BdePerformanceRoute
  BdeProfileRoute: typeof BdeProfileRoute
  BdeReportsRoute: typeof BdeReportsRoute
  BdeSettingsRoute: typeof BdeSettingsRoute
  BdeSupportRoute: typeof BdeSupportRoute
  DistributorCommissionsRoute: typeof DistributorCommissionsRoute
  DistributorDashboardRoute: typeof DistributorDashboardRoute
  DistributorFeedbackRoute: typeof DistributorFeedbackRoute
  DistributorNetworkRoute: typeof DistributorNetworkRoute
  DistributorOfficersRoute: typeof DistributorOfficersRouteWithChildren
  DistributorReportsRoute: typeof DistributorReportsRoute
  DistributorRetailersRoute: typeof DistributorRetailersRouteWithChildren
  DistributorSalesDashboardRoute: typeof DistributorSalesDashboardRoute
  DistributorServicesRoute: typeof DistributorServicesRouteWithChildren
  DistributorSettingsRoute: typeof DistributorSettingsRoute
  DistributorSupportRoute: typeof DistributorSupportRoute
  DroAttendanceRoute: typeof DroAttendanceRoute
  DroCatalogRoute: typeof DroCatalogRoute
  DroDashboardRoute: typeof DroDashboardRoute
  DroFeedbackRoute: typeof DroFeedbackRoute
  DroFeedbackDeskRoute: typeof DroFeedbackDeskRoute
  DroNotificationsRoute: typeof DroNotificationsRoute
  DroProfileRoute: typeof DroProfileRoute
  DroRetailersRoute: typeof DroRetailersRouteWithChildren
  DroServicesRoute: typeof DroServicesRoute
  DroSupportRoute: typeof DroSupportRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrDashboardRoute: typeof HrDashboardRoute
  HrEmployeesRoute: typeof HrEmployeesRoute
  HrFeedbackRoute: typeof HrFeedbackRoute
  HrLeaveRoute: typeof HrLeaveRoute
  HrOnboardingRoute: typeof HrOnboardingRoute
  HrPayrollRoute: typeof HrPayrollRoute
  HrPerformanceRoute: typeof HrPerformanceRoute
  HrProfileRoute: typeof HrProfileRoute
  HrRecruitmentRoute: typeof HrRecruitmentRoute
  HrReportsRoute: typeof HrReportsRoute
  HrSettingsRoute: typeof HrSettingsRoute
  HrSupportRoute: typeof HrSupportRoute
  HrTrainingRoute: typeof HrTrainingRoute
  QcApprovedRoute: typeof QcApprovedRoute
  QcChangePasswordRoute: typeof QcChangePasswordRoute
  QcDashboardRoute: typeof QcDashboardRoute
  QcDocumentSearchRoute: typeof QcDocumentSearchRoute
  QcFeedbackRoute: typeof QcFeedbackRoute
  QcFlaggedRoute: typeof QcFlaggedRoute
  QcKycQueueRoute: typeof QcKycQueueRoute
  QcProfileRoute: typeof QcProfileRoute
  QcReportsRoute: typeof QcReportsRoute
  QcReviewersRoute: typeof QcReviewersRoute
  QcSettingsRoute: typeof QcSettingsRoute
  QcSupportRoute: typeof QcSupportRoute
  TroAttendanceRoute: typeof TroAttendanceRoute
  TroCatalogRoute: typeof TroCatalogRoute
  TroDashboardRoute: typeof TroDashboardRoute
  TroFeedbackRoute: typeof TroFeedbackRoute
  TroFeedbackDeskRoute: typeof TroFeedbackDeskRoute
  TroNotificationsRoute: typeof TroNotificationsRoute
  TroProfileRoute: typeof TroProfileRoute
  TroRetailersRoute: typeof TroRetailersRouteWithChildren
  TroServicesRoute: typeof TroServicesRoute
  TroSupportRoute: typeof TroSupportRoute
  QcKycReviewIdRoute: typeof QcKycReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-kyc': {
      id: '/video-kyc'
      path: '/video-kyc'
      fullPath: '/video-kyc'
      preLoaderRoute: typeof VideoKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro-login': {
      id: '/tro-login'
      path: '/tro-login'
      fullPath: '/tro-login'
      preLoaderRoute: typeof TroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-application': {
      id: '/track-application'
      path: '/track-application'
      fullPath: '/track-application'
      preLoaderRoute: typeof TrackApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telecaller-login': {
      id: '/telecaller-login'
      path: '/telecaller-login'
      fullPath: '/telecaller-login'
      preLoaderRoute: typeof TelecallerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telecaller': {
      id: '/telecaller'
      path: '/telecaller'
      fullPath: '/telecaller'
      preLoaderRoute: typeof TelecallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc-login': {
      id: '/qc-login'
      path: '/qc-login'
      fullPath: '/qc-login'
      preLoaderRoute: typeof QcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pan': {
      id: '/pan'
      path: '/pan'
      fullPath: '/pan'
      preLoaderRoute: typeof PanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-service-request': {
      id: '/new-service-request'
      path: '/new-service-request'
      fullPath: '/new-service-request'
      preLoaderRoute: typeof NewServiceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-transfer': {
      id: '/money-transfer'
      path: '/money-transfer'
      fullPath: '/money-transfer'
      preLoaderRoute: typeof MoneyTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-distributor-login': {
      id: '/master-distributor-login'
      path: '/master-distributor-login'
      fullPath: '/master-distributor-login'
      preLoaderRoute: typeof MasterDistributorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-login': {
      id: '/hr-login'
      path: '/hr-login'
      fullPath: '/hr-login'
      preLoaderRoute: typeof HrLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov-services': {
      id: '/gov-services'
      path: '/gov-services'
      fullPath: '/gov-services'
      preLoaderRoute: typeof GovServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro-login': {
      id: '/dro-login'
      path: '/dro-login'
      fullPath: '/dro-login'
      preLoaderRoute: typeof DroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-login': {
      id: '/distributor-login'
      path: '/distributor-login'
      fullPath: '/distributor-login'
      preLoaderRoute: typeof DistributorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-reg': {
      id: '/business-reg'
      path: '/business-reg'
      fullPath: '/business-reg'
      preLoaderRoute: typeof BusinessRegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde-login': {
      id: '/bde-login'
      path: '/bde-login'
      fullPath: '/bde-login'
      preLoaderRoute: typeof BdeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbps': {
      id: '/bbps'
      path: '/bbps'
      fullPath: '/bbps'
      preLoaderRoute: typeof BbpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeps-activation': {
      id: '/aeps-activation'
      path: '/aeps-activation'
      fullPath: '/aeps-activation'
      preLoaderRoute: typeof AepsActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeps': {
      id: '/aeps'
      path: '/aeps'
      fullPath: '/aeps'
      preLoaderRoute: typeof AepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant-login': {
      id: '/accountant-login'
      path: '/accountant-login'
      fullPath: '/accountant-login'
      preLoaderRoute: typeof AccountantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/support': {
      id: '/tro/support'
      path: '/tro/support'
      fullPath: '/tro/support'
      preLoaderRoute: typeof TroSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/services': {
      id: '/tro/services'
      path: '/tro/services'
      fullPath: '/tro/services'
      preLoaderRoute: typeof TroServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/retailers': {
      id: '/tro/retailers'
      path: '/tro/retailers'
      fullPath: '/tro/retailers'
      preLoaderRoute: typeof TroRetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/profile': {
      id: '/tro/profile'
      path: '/tro/profile'
      fullPath: '/tro/profile'
      preLoaderRoute: typeof TroProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/notifications': {
      id: '/tro/notifications'
      path: '/tro/notifications'
      fullPath: '/tro/notifications'
      preLoaderRoute: typeof TroNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/feedback-desk': {
      id: '/tro/feedback-desk'
      path: '/tro/feedback-desk'
      fullPath: '/tro/feedback-desk'
      preLoaderRoute: typeof TroFeedbackDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/feedback': {
      id: '/tro/feedback'
      path: '/tro/feedback'
      fullPath: '/tro/feedback'
      preLoaderRoute: typeof TroFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/dashboard': {
      id: '/tro/dashboard'
      path: '/tro/dashboard'
      fullPath: '/tro/dashboard'
      preLoaderRoute: typeof TroDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/catalog': {
      id: '/tro/catalog'
      path: '/tro/catalog'
      fullPath: '/tro/catalog'
      preLoaderRoute: typeof TroCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro/attendance': {
      id: '/tro/attendance'
      path: '/tro/attendance'
      fullPath: '/tro/attendance'
      preLoaderRoute: typeof TroAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/support': {
      id: '/qc/support'
      path: '/qc/support'
      fullPath: '/qc/support'
      preLoaderRoute: typeof QcSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/settings': {
      id: '/qc/settings'
      path: '/qc/settings'
      fullPath: '/qc/settings'
      preLoaderRoute: typeof QcSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/reviewers': {
      id: '/qc/reviewers'
      path: '/qc/reviewers'
      fullPath: '/qc/reviewers'
      preLoaderRoute: typeof QcReviewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/reports': {
      id: '/qc/reports'
      path: '/qc/reports'
      fullPath: '/qc/reports'
      preLoaderRoute: typeof QcReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/profile': {
      id: '/qc/profile'
      path: '/qc/profile'
      fullPath: '/qc/profile'
      preLoaderRoute: typeof QcProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/kyc-queue': {
      id: '/qc/kyc-queue'
      path: '/qc/kyc-queue'
      fullPath: '/qc/kyc-queue'
      preLoaderRoute: typeof QcKycQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/flagged': {
      id: '/qc/flagged'
      path: '/qc/flagged'
      fullPath: '/qc/flagged'
      preLoaderRoute: typeof QcFlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/feedback': {
      id: '/qc/feedback'
      path: '/qc/feedback'
      fullPath: '/qc/feedback'
      preLoaderRoute: typeof QcFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/document-search': {
      id: '/qc/document-search'
      path: '/qc/document-search'
      fullPath: '/qc/document-search'
      preLoaderRoute: typeof QcDocumentSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/dashboard': {
      id: '/qc/dashboard'
      path: '/qc/dashboard'
      fullPath: '/qc/dashboard'
      preLoaderRoute: typeof QcDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/change-password': {
      id: '/qc/change-password'
      path: '/qc/change-password'
      fullPath: '/qc/change-password'
      preLoaderRoute: typeof QcChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/approved': {
      id: '/qc/approved'
      path: '/qc/approved'
      fullPath: '/qc/approved'
      preLoaderRoute: typeof QcApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/training': {
      id: '/hr/training'
      path: '/hr/training'
      fullPath: '/hr/training'
      preLoaderRoute: typeof HrTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/support': {
      id: '/hr/support'
      path: '/hr/support'
      fullPath: '/hr/support'
      preLoaderRoute: typeof HrSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/settings': {
      id: '/hr/settings'
      path: '/hr/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof HrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/reports': {
      id: '/hr/reports'
      path: '/hr/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof HrReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/recruitment': {
      id: '/hr/recruitment'
      path: '/hr/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof HrRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/profile': {
      id: '/hr/profile'
      path: '/hr/profile'
      fullPath: '/hr/profile'
      preLoaderRoute: typeof HrProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/performance': {
      id: '/hr/performance'
      path: '/hr/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof HrPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/onboarding': {
      id: '/hr/onboarding'
      path: '/hr/onboarding'
      fullPath: '/hr/onboarding'
      preLoaderRoute: typeof HrOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave': {
      id: '/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof HrLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/feedback': {
      id: '/hr/feedback'
      path: '/hr/feedback'
      fullPath: '/hr/feedback'
      preLoaderRoute: typeof HrFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/dashboard': {
      id: '/hr/dashboard'
      path: '/hr/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/support': {
      id: '/dro/support'
      path: '/dro/support'
      fullPath: '/dro/support'
      preLoaderRoute: typeof DroSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/services': {
      id: '/dro/services'
      path: '/dro/services'
      fullPath: '/dro/services'
      preLoaderRoute: typeof DroServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/retailers': {
      id: '/dro/retailers'
      path: '/dro/retailers'
      fullPath: '/dro/retailers'
      preLoaderRoute: typeof DroRetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/profile': {
      id: '/dro/profile'
      path: '/dro/profile'
      fullPath: '/dro/profile'
      preLoaderRoute: typeof DroProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/notifications': {
      id: '/dro/notifications'
      path: '/dro/notifications'
      fullPath: '/dro/notifications'
      preLoaderRoute: typeof DroNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/feedback-desk': {
      id: '/dro/feedback-desk'
      path: '/dro/feedback-desk'
      fullPath: '/dro/feedback-desk'
      preLoaderRoute: typeof DroFeedbackDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/feedback': {
      id: '/dro/feedback'
      path: '/dro/feedback'
      fullPath: '/dro/feedback'
      preLoaderRoute: typeof DroFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/dashboard': {
      id: '/dro/dashboard'
      path: '/dro/dashboard'
      fullPath: '/dro/dashboard'
      preLoaderRoute: typeof DroDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/catalog': {
      id: '/dro/catalog'
      path: '/dro/catalog'
      fullPath: '/dro/catalog'
      preLoaderRoute: typeof DroCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/attendance': {
      id: '/dro/attendance'
      path: '/dro/attendance'
      fullPath: '/dro/attendance'
      preLoaderRoute: typeof DroAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/support': {
      id: '/distributor/support'
      path: '/distributor/support'
      fullPath: '/distributor/support'
      preLoaderRoute: typeof DistributorSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/settings': {
      id: '/distributor/settings'
      path: '/distributor/settings'
      fullPath: '/distributor/settings'
      preLoaderRoute: typeof DistributorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/services': {
      id: '/distributor/services'
      path: '/distributor/services'
      fullPath: '/distributor/services'
      preLoaderRoute: typeof DistributorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/sales-dashboard': {
      id: '/distributor/sales-dashboard'
      path: '/distributor/sales-dashboard'
      fullPath: '/distributor/sales-dashboard'
      preLoaderRoute: typeof DistributorSalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/retailers': {
      id: '/distributor/retailers'
      path: '/distributor/retailers'
      fullPath: '/distributor/retailers'
      preLoaderRoute: typeof DistributorRetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/reports': {
      id: '/distributor/reports'
      path: '/distributor/reports'
      fullPath: '/distributor/reports'
      preLoaderRoute: typeof DistributorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/officers': {
      id: '/distributor/officers'
      path: '/distributor/officers'
      fullPath: '/distributor/officers'
      preLoaderRoute: typeof DistributorOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/network': {
      id: '/distributor/network'
      path: '/distributor/network'
      fullPath: '/distributor/network'
      preLoaderRoute: typeof DistributorNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/feedback': {
      id: '/distributor/feedback'
      path: '/distributor/feedback'
      fullPath: '/distributor/feedback'
      preLoaderRoute: typeof DistributorFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/dashboard': {
      id: '/distributor/dashboard'
      path: '/distributor/dashboard'
      fullPath: '/distributor/dashboard'
      preLoaderRoute: typeof DistributorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/commissions': {
      id: '/distributor/commissions'
      path: '/distributor/commissions'
      fullPath: '/distributor/commissions'
      preLoaderRoute: typeof DistributorCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/support': {
      id: '/bde/support'
      path: '/bde/support'
      fullPath: '/bde/support'
      preLoaderRoute: typeof BdeSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/settings': {
      id: '/bde/settings'
      path: '/bde/settings'
      fullPath: '/bde/settings'
      preLoaderRoute: typeof BdeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/reports': {
      id: '/bde/reports'
      path: '/bde/reports'
      fullPath: '/bde/reports'
      preLoaderRoute: typeof BdeReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/profile': {
      id: '/bde/profile'
      path: '/bde/profile'
      fullPath: '/bde/profile'
      preLoaderRoute: typeof BdeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/performance': {
      id: '/bde/performance'
      path: '/bde/performance'
      fullPath: '/bde/performance'
      preLoaderRoute: typeof BdePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/opportunities': {
      id: '/bde/opportunities'
      path: '/bde/opportunities'
      fullPath: '/bde/opportunities'
      preLoaderRoute: typeof BdeOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/network': {
      id: '/bde/network'
      path: '/bde/network'
      fullPath: '/bde/network'
      preLoaderRoute: typeof BdeNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/merchants': {
      id: '/bde/merchants'
      path: '/bde/merchants'
      fullPath: '/bde/merchants'
      preLoaderRoute: typeof BdeMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/leads': {
      id: '/bde/leads'
      path: '/bde/leads'
      fullPath: '/bde/leads'
      preLoaderRoute: typeof BdeLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/feedback': {
      id: '/bde/feedback'
      path: '/bde/feedback'
      fullPath: '/bde/feedback'
      preLoaderRoute: typeof BdeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/dashboard': {
      id: '/bde/dashboard'
      path: '/bde/dashboard'
      fullPath: '/bde/dashboard'
      preLoaderRoute: typeof BdeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/withdrawals': {
      id: '/accountant/withdrawals'
      path: '/accountant/withdrawals'
      fullPath: '/accountant/withdrawals'
      preLoaderRoute: typeof AccountantWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/wallet-requests': {
      id: '/accountant/wallet-requests'
      path: '/accountant/wallet-requests'
      fullPath: '/accountant/wallet-requests'
      preLoaderRoute: typeof AccountantWalletRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/support': {
      id: '/accountant/support'
      path: '/accountant/support'
      fullPath: '/accountant/support'
      preLoaderRoute: typeof AccountantSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/settings': {
      id: '/accountant/settings'
      path: '/accountant/settings'
      fullPath: '/accountant/settings'
      preLoaderRoute: typeof AccountantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/services': {
      id: '/accountant/services'
      path: '/accountant/services'
      fullPath: '/accountant/services'
      preLoaderRoute: typeof AccountantServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/registrations': {
      id: '/accountant/registrations'
      path: '/accountant/registrations'
      fullPath: '/accountant/registrations'
      preLoaderRoute: typeof AccountantRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/profile': {
      id: '/accountant/profile'
      path: '/accountant/profile'
      fullPath: '/accountant/profile'
      preLoaderRoute: typeof AccountantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/main-recharge': {
      id: '/accountant/main-recharge'
      path: '/accountant/main-recharge'
      fullPath: '/accountant/main-recharge'
      preLoaderRoute: typeof AccountantMainRechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/ledger': {
      id: '/accountant/ledger'
      path: '/accountant/ledger'
      fullPath: '/accountant/ledger'
      preLoaderRoute: typeof AccountantLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/feedback': {
      id: '/accountant/feedback'
      path: '/accountant/feedback'
      fullPath: '/accountant/feedback'
      preLoaderRoute: typeof AccountantFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/dashboard': {
      id: '/accountant/dashboard'
      path: '/accountant/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof AccountantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/change-password': {
      id: '/accountant/change-password'
      path: '/accountant/change-password'
      fullPath: '/accountant/change-password'
      preLoaderRoute: typeof AccountantChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor/retailers/': {
      id: '/distributor/retailers/'
      path: '/'
      fullPath: '/distributor/retailers/'
      preLoaderRoute: typeof DistributorRetailersIndexRouteImport
      parentRoute: typeof DistributorRetailersRoute
    }
    '/tro/retailers/$id': {
      id: '/tro/retailers/$id'
      path: '/$id'
      fullPath: '/tro/retailers/$id'
      preLoaderRoute: typeof TroRetailersIdRouteImport
      parentRoute: typeof TroRetailersRoute
    }
    '/qc/kyc-review/$id': {
      id: '/qc/kyc-review/$id'
      path: '/qc/kyc-review/$id'
      fullPath: '/qc/kyc-review/$id'
      preLoaderRoute: typeof QcKycReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro/retailers/$id': {
      id: '/dro/retailers/$id'
      path: '/$id'
      fullPath: '/dro/retailers/$id'
      preLoaderRoute: typeof DroRetailersIdRouteImport
      parentRoute: typeof DroRetailersRoute
    }
    '/distributor/services/$key': {
      id: '/distributor/services/$key'
      path: '/$key'
      fullPath: '/distributor/services/$key'
      preLoaderRoute: typeof DistributorServicesKeyRouteImport
      parentRoute: typeof DistributorServicesRoute
    }
    '/distributor/retailers/$id': {
      id: '/distributor/retailers/$id'
      path: '/$id'
      fullPath: '/distributor/retailers/$id'
      preLoaderRoute: typeof DistributorRetailersIdRouteImport
      parentRoute: typeof DistributorRetailersRoute
    }
    '/distributor/officers/$id': {
      id: '/distributor/officers/$id'
      path: '/$id'
      fullPath: '/distributor/officers/$id'
      preLoaderRoute: typeof DistributorOfficersIdRouteImport
      parentRoute: typeof DistributorOfficersRoute
    }
  }
}

interface DistributorOfficersRouteChildren {
  DistributorOfficersIdRoute: typeof DistributorOfficersIdRoute
}

const DistributorOfficersRouteChildren: DistributorOfficersRouteChildren = {
  DistributorOfficersIdRoute: DistributorOfficersIdRoute,
}

const DistributorOfficersRouteWithChildren =
  DistributorOfficersRoute._addFileChildren(DistributorOfficersRouteChildren)

interface DistributorRetailersRouteChildren {
  DistributorRetailersIdRoute: typeof DistributorRetailersIdRoute
  DistributorRetailersIndexRoute: typeof DistributorRetailersIndexRoute
}

const DistributorRetailersRouteChildren: DistributorRetailersRouteChildren = {
  DistributorRetailersIdRoute: DistributorRetailersIdRoute,
  DistributorRetailersIndexRoute: DistributorRetailersIndexRoute,
}

const DistributorRetailersRouteWithChildren =
  DistributorRetailersRoute._addFileChildren(DistributorRetailersRouteChildren)

interface DistributorServicesRouteChildren {
  DistributorServicesKeyRoute: typeof DistributorServicesKeyRoute
}

const DistributorServicesRouteChildren: DistributorServicesRouteChildren = {
  DistributorServicesKeyRoute: DistributorServicesKeyRoute,
}

const DistributorServicesRouteWithChildren =
  DistributorServicesRoute._addFileChildren(DistributorServicesRouteChildren)

interface DroRetailersRouteChildren {
  DroRetailersIdRoute: typeof DroRetailersIdRoute
}

const DroRetailersRouteChildren: DroRetailersRouteChildren = {
  DroRetailersIdRoute: DroRetailersIdRoute,
}

const DroRetailersRouteWithChildren = DroRetailersRoute._addFileChildren(
  DroRetailersRouteChildren,
)

interface TroRetailersRouteChildren {
  TroRetailersIdRoute: typeof TroRetailersIdRoute
}

const TroRetailersRouteChildren: TroRetailersRouteChildren = {
  TroRetailersIdRoute: TroRetailersIdRoute,
}

const TroRetailersRouteWithChildren = TroRetailersRoute._addFileChildren(
  TroRetailersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantLoginRoute: AccountantLoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  AepsRoute: AepsRoute,
  AepsActivationRoute: AepsActivationRoute,
  ApplicationsRoute: ApplicationsRoute,
  BbpsRoute: BbpsRoute,
  BdeLoginRoute: BdeLoginRoute,
  BusinessRegRoute: BusinessRegRoute,
  DashboardRoute: DashboardRoute,
  DistributorLoginRoute: DistributorLoginRoute,
  DroLoginRoute: DroLoginRoute,
  FeedbackRoute: FeedbackRoute,
  GetStartedRoute: GetStartedRoute,
  GovServicesRoute: GovServicesRoute,
  GstRoute: GstRoute,
  HrLoginRoute: HrLoginRoute,
  LoginRoute: LoginRoute,
  MasterDistributorLoginRoute: MasterDistributorLoginRoute,
  MoneyTransferRoute: MoneyTransferRoute,
  NewServiceRequestRoute: NewServiceRequestRoute,
  NotificationsRoute: NotificationsRoute,
  PanRoute: PanRoute,
  PortalsRoute: PortalsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QcLoginRoute: QcLoginRoute,
  RechargeRoute: RechargeRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TelecallerRoute: TelecallerRoute,
  TelecallerLoginRoute: TelecallerLoginRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackApplicationRoute: TrackApplicationRoute,
  TransactionsRoute: TransactionsRoute,
  TroLoginRoute: TroLoginRoute,
  VideoKycRoute: VideoKycRoute,
  WalletRoute: WalletRoute,
  AccountantChangePasswordRoute: AccountantChangePasswordRoute,
  AccountantDashboardRoute: AccountantDashboardRoute,
  AccountantFeedbackRoute: AccountantFeedbackRoute,
  AccountantLedgerRoute: AccountantLedgerRoute,
  AccountantMainRechargeRoute: AccountantMainRechargeRoute,
  AccountantProfileRoute: AccountantProfileRoute,
  AccountantRegistrationsRoute: AccountantRegistrationsRoute,
  AccountantServicesRoute: AccountantServicesRoute,
  AccountantSettingsRoute: AccountantSettingsRoute,
  AccountantSupportRoute: AccountantSupportRoute,
  AccountantWalletRequestsRoute: AccountantWalletRequestsRoute,
  AccountantWithdrawalsRoute: AccountantWithdrawalsRoute,
  BdeDashboardRoute: BdeDashboardRoute,
  BdeFeedbackRoute: BdeFeedbackRoute,
  BdeLeadsRoute: BdeLeadsRoute,
  BdeMerchantsRoute: BdeMerchantsRoute,
  BdeNetworkRoute: BdeNetworkRoute,
  BdeOpportunitiesRoute: BdeOpportunitiesRoute,
  BdePerformanceRoute: BdePerformanceRoute,
  BdeProfileRoute: BdeProfileRoute,
  BdeReportsRoute: BdeReportsRoute,
  BdeSettingsRoute: BdeSettingsRoute,
  BdeSupportRoute: BdeSupportRoute,
  DistributorCommissionsRoute: DistributorCommissionsRoute,
  DistributorDashboardRoute: DistributorDashboardRoute,
  DistributorFeedbackRoute: DistributorFeedbackRoute,
  DistributorNetworkRoute: DistributorNetworkRoute,
  DistributorOfficersRoute: DistributorOfficersRouteWithChildren,
  DistributorReportsRoute: DistributorReportsRoute,
  DistributorRetailersRoute: DistributorRetailersRouteWithChildren,
  DistributorSalesDashboardRoute: DistributorSalesDashboardRoute,
  DistributorServicesRoute: DistributorServicesRouteWithChildren,
  DistributorSettingsRoute: DistributorSettingsRoute,
  DistributorSupportRoute: DistributorSupportRoute,
  DroAttendanceRoute: DroAttendanceRoute,
  DroCatalogRoute: DroCatalogRoute,
  DroDashboardRoute: DroDashboardRoute,
  DroFeedbackRoute: DroFeedbackRoute,
  DroFeedbackDeskRoute: DroFeedbackDeskRoute,
  DroNotificationsRoute: DroNotificationsRoute,
  DroProfileRoute: DroProfileRoute,
  DroRetailersRoute: DroRetailersRouteWithChildren,
  DroServicesRoute: DroServicesRoute,
  DroSupportRoute: DroSupportRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrDashboardRoute: HrDashboardRoute,
  HrEmployeesRoute: HrEmployeesRoute,
  HrFeedbackRoute: HrFeedbackRoute,
  HrLeaveRoute: HrLeaveRoute,
  HrOnboardingRoute: HrOnboardingRoute,
  HrPayrollRoute: HrPayrollRoute,
  HrPerformanceRoute: HrPerformanceRoute,
  HrProfileRoute: HrProfileRoute,
  HrRecruitmentRoute: HrRecruitmentRoute,
  HrReportsRoute: HrReportsRoute,
  HrSettingsRoute: HrSettingsRoute,
  HrSupportRoute: HrSupportRoute,
  HrTrainingRoute: HrTrainingRoute,
  QcApprovedRoute: QcApprovedRoute,
  QcChangePasswordRoute: QcChangePasswordRoute,
  QcDashboardRoute: QcDashboardRoute,
  QcDocumentSearchRoute: QcDocumentSearchRoute,
  QcFeedbackRoute: QcFeedbackRoute,
  QcFlaggedRoute: QcFlaggedRoute,
  QcKycQueueRoute: QcKycQueueRoute,
  QcProfileRoute: QcProfileRoute,
  QcReportsRoute: QcReportsRoute,
  QcReviewersRoute: QcReviewersRoute,
  QcSettingsRoute: QcSettingsRoute,
  QcSupportRoute: QcSupportRoute,
  TroAttendanceRoute: TroAttendanceRoute,
  TroCatalogRoute: TroCatalogRoute,
  TroDashboardRoute: TroDashboardRoute,
  TroFeedbackRoute: TroFeedbackRoute,
  TroFeedbackDeskRoute: TroFeedbackDeskRoute,
  TroNotificationsRoute: TroNotificationsRoute,
  TroProfileRoute: TroProfileRoute,
  TroRetailersRoute: TroRetailersRouteWithChildren,
  TroServicesRoute: TroServicesRoute,
  TroSupportRoute: TroSupportRoute,
  QcKycReviewIdRoute: QcKycReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
