/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VideoKycRouteImport } from './routes/video-kyc'
import { Route as TroLoginRouteImport } from './routes/tro-login'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TrackApplicationRouteImport } from './routes/track-application'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as QcLoginRouteImport } from './routes/qc-login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PanRouteImport } from './routes/pan'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewServiceRequestRouteImport } from './routes/new-service-request'
import { Route as MoneyTransferRouteImport } from './routes/money-transfer'
import { Route as MasterDistributorLoginRouteImport } from './routes/master-distributor-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GstRouteImport } from './routes/gst'
import { Route as GovServicesRouteImport } from './routes/gov-services'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DroLoginRouteImport } from './routes/dro-login'
import { Route as DistributorLoginRouteImport } from './routes/distributor-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BusinessRegRouteImport } from './routes/business-reg'
import { Route as BbpsRouteImport } from './routes/bbps'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AepsActivationRouteImport } from './routes/aeps-activation'
import { Route as AepsRouteImport } from './routes/aeps'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AccountantLoginRouteImport } from './routes/accountant-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QcSettingsRouteImport } from './routes/qc.settings'
import { Route as QcReviewersRouteImport } from './routes/qc.reviewers'
import { Route as QcReportsRouteImport } from './routes/qc.reports'
import { Route as QcProfileRouteImport } from './routes/qc.profile'
import { Route as QcKycQueueRouteImport } from './routes/qc.kyc-queue'
import { Route as QcFlaggedRouteImport } from './routes/qc.flagged'
import { Route as QcDocumentSearchRouteImport } from './routes/qc.document-search'
import { Route as QcDashboardRouteImport } from './routes/qc.dashboard'
import { Route as QcChangePasswordRouteImport } from './routes/qc.change-password'
import { Route as QcApprovedRouteImport } from './routes/qc.approved'
import { Route as AccountantWithdrawalsRouteImport } from './routes/accountant.withdrawals'
import { Route as AccountantWalletRequestsRouteImport } from './routes/accountant.wallet-requests'
import { Route as AccountantSettingsRouteImport } from './routes/accountant.settings'
import { Route as AccountantServicesRouteImport } from './routes/accountant.services'
import { Route as AccountantRegistrationsRouteImport } from './routes/accountant.registrations'
import { Route as AccountantProfileRouteImport } from './routes/accountant.profile'
import { Route as AccountantMainRechargeRouteImport } from './routes/accountant.main-recharge'
import { Route as AccountantDashboardRouteImport } from './routes/accountant.dashboard'
import { Route as AccountantChangePasswordRouteImport } from './routes/accountant.change-password'
import { Route as QcKycReviewIdRouteImport } from './routes/qc.kyc-review.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoKycRoute = VideoKycRouteImport.update({
  id: '/video-kyc',
  path: '/video-kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const TroLoginRoute = TroLoginRouteImport.update({
  id: '/tro-login',
  path: '/tro-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackApplicationRoute = TrackApplicationRouteImport.update({
  id: '/track-application',
  path: '/track-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const QcLoginRoute = QcLoginRouteImport.update({
  id: '/qc-login',
  path: '/qc-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PanRoute = PanRouteImport.update({
  id: '/pan',
  path: '/pan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewServiceRequestRoute = NewServiceRequestRouteImport.update({
  id: '/new-service-request',
  path: '/new-service-request',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyTransferRoute = MoneyTransferRouteImport.update({
  id: '/money-transfer',
  path: '/money-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDistributorLoginRoute = MasterDistributorLoginRouteImport.update({
  id: '/master-distributor-login',
  path: '/master-distributor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const GovServicesRoute = GovServicesRouteImport.update({
  id: '/gov-services',
  path: '/gov-services',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DroLoginRoute = DroLoginRouteImport.update({
  id: '/dro-login',
  path: '/dro-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorLoginRoute = DistributorLoginRouteImport.update({
  id: '/distributor-login',
  path: '/distributor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegRoute = BusinessRegRouteImport.update({
  id: '/business-reg',
  path: '/business-reg',
  getParentRoute: () => rootRouteImport,
} as any)
const BbpsRoute = BbpsRouteImport.update({
  id: '/bbps',
  path: '/bbps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AepsActivationRoute = AepsActivationRouteImport.update({
  id: '/aeps-activation',
  path: '/aeps-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AepsRoute = AepsRouteImport.update({
  id: '/aeps',
  path: '/aeps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantLoginRoute = AccountantLoginRouteImport.update({
  id: '/accountant-login',
  path: '/accountant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QcSettingsRoute = QcSettingsRouteImport.update({
  id: '/qc/settings',
  path: '/qc/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QcReviewersRoute = QcReviewersRouteImport.update({
  id: '/qc/reviewers',
  path: '/qc/reviewers',
  getParentRoute: () => rootRouteImport,
} as any)
const QcReportsRoute = QcReportsRouteImport.update({
  id: '/qc/reports',
  path: '/qc/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QcProfileRoute = QcProfileRouteImport.update({
  id: '/qc/profile',
  path: '/qc/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QcKycQueueRoute = QcKycQueueRouteImport.update({
  id: '/qc/kyc-queue',
  path: '/qc/kyc-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const QcFlaggedRoute = QcFlaggedRouteImport.update({
  id: '/qc/flagged',
  path: '/qc/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const QcDocumentSearchRoute = QcDocumentSearchRouteImport.update({
  id: '/qc/document-search',
  path: '/qc/document-search',
  getParentRoute: () => rootRouteImport,
} as any)
const QcDashboardRoute = QcDashboardRouteImport.update({
  id: '/qc/dashboard',
  path: '/qc/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QcChangePasswordRoute = QcChangePasswordRouteImport.update({
  id: '/qc/change-password',
  path: '/qc/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QcApprovedRoute = QcApprovedRouteImport.update({
  id: '/qc/approved',
  path: '/qc/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantWithdrawalsRoute = AccountantWithdrawalsRouteImport.update({
  id: '/accountant/withdrawals',
  path: '/accountant/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantWalletRequestsRoute =
  AccountantWalletRequestsRouteImport.update({
    id: '/accountant/wallet-requests',
    path: '/accountant/wallet-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountantSettingsRoute = AccountantSettingsRouteImport.update({
  id: '/accountant/settings',
  path: '/accountant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantServicesRoute = AccountantServicesRouteImport.update({
  id: '/accountant/services',
  path: '/accountant/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRegistrationsRoute = AccountantRegistrationsRouteImport.update({
  id: '/accountant/registrations',
  path: '/accountant/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantProfileRoute = AccountantProfileRouteImport.update({
  id: '/accountant/profile',
  path: '/accountant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantMainRechargeRoute = AccountantMainRechargeRouteImport.update({
  id: '/accountant/main-recharge',
  path: '/accountant/main-recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantDashboardRoute = AccountantDashboardRouteImport.update({
  id: '/accountant/dashboard',
  path: '/accountant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantChangePasswordRoute =
  AccountantChangePasswordRouteImport.update({
    id: '/accountant/change-password',
    path: '/accountant/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const QcKycReviewIdRoute = QcKycReviewIdRouteImport.update({
  id: '/qc/kyc-review/$id',
  path: '/qc/kyc-review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant-login': typeof AccountantLoginRoute
  '/admin-login': typeof AdminLoginRoute
  '/aeps': typeof AepsRoute
  '/aeps-activation': typeof AepsActivationRoute
  '/applications': typeof ApplicationsRoute
  '/bbps': typeof BbpsRoute
  '/business-reg': typeof BusinessRegRoute
  '/dashboard': typeof DashboardRoute
  '/distributor-login': typeof DistributorLoginRoute
  '/dro-login': typeof DroLoginRoute
  '/get-started': typeof GetStartedRoute
  '/gov-services': typeof GovServicesRoute
  '/gst': typeof GstRoute
  '/login': typeof LoginRoute
  '/master-distributor-login': typeof MasterDistributorLoginRoute
  '/money-transfer': typeof MoneyTransferRoute
  '/new-service-request': typeof NewServiceRequestRoute
  '/notifications': typeof NotificationsRoute
  '/pan': typeof PanRoute
  '/portals': typeof PortalsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qc-login': typeof QcLoginRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-application': typeof TrackApplicationRoute
  '/transactions': typeof TransactionsRoute
  '/tro-login': typeof TroLoginRoute
  '/video-kyc': typeof VideoKycRoute
  '/wallet': typeof WalletRoute
  '/accountant/change-password': typeof AccountantChangePasswordRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/accountant/main-recharge': typeof AccountantMainRechargeRoute
  '/accountant/profile': typeof AccountantProfileRoute
  '/accountant/registrations': typeof AccountantRegistrationsRoute
  '/accountant/services': typeof AccountantServicesRoute
  '/accountant/settings': typeof AccountantSettingsRoute
  '/accountant/wallet-requests': typeof AccountantWalletRequestsRoute
  '/accountant/withdrawals': typeof AccountantWithdrawalsRoute
  '/qc/approved': typeof QcApprovedRoute
  '/qc/change-password': typeof QcChangePasswordRoute
  '/qc/dashboard': typeof QcDashboardRoute
  '/qc/document-search': typeof QcDocumentSearchRoute
  '/qc/flagged': typeof QcFlaggedRoute
  '/qc/kyc-queue': typeof QcKycQueueRoute
  '/qc/profile': typeof QcProfileRoute
  '/qc/reports': typeof QcReportsRoute
  '/qc/reviewers': typeof QcReviewersRoute
  '/qc/settings': typeof QcSettingsRoute
  '/qc/kyc-review/$id': typeof QcKycReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/kyc-review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/kyc-review/$id'
  id:
    | '__root__'
    | '/'
    | '/accountant-login'
    | '/admin-login'
    | '/aeps'
    | '/aeps-activation'
    | '/applications'
    | '/bbps'
    | '/business-reg'
    | '/dashboard'
    | '/distributor-login'
    | '/dro-login'
    | '/get-started'
    | '/gov-services'
    | '/gst'
    | '/login'
    | '/master-distributor-login'
    | '/money-transfer'
    | '/new-service-request'
    | '/notifications'
    | '/pan'
    | '/portals'
    | '/privacy-policy'
    | '/qc-login'
    | '/recharge'
    | '/register'
    | '/reports'
    | '/services'
    | '/settings'
    | '/support'
    | '/terms-and-conditions'
    | '/track-application'
    | '/transactions'
    | '/tro-login'
    | '/video-kyc'
    | '/wallet'
    | '/accountant/change-password'
    | '/accountant/dashboard'
    | '/accountant/main-recharge'
    | '/accountant/profile'
    | '/accountant/registrations'
    | '/accountant/services'
    | '/accountant/settings'
    | '/accountant/wallet-requests'
    | '/accountant/withdrawals'
    | '/qc/approved'
    | '/qc/change-password'
    | '/qc/dashboard'
    | '/qc/document-search'
    | '/qc/flagged'
    | '/qc/kyc-queue'
    | '/qc/profile'
    | '/qc/reports'
    | '/qc/reviewers'
    | '/qc/settings'
    | '/qc/kyc-review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantLoginRoute: typeof AccountantLoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AepsRoute: typeof AepsRoute
  AepsActivationRoute: typeof AepsActivationRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BbpsRoute: typeof BbpsRoute
  BusinessRegRoute: typeof BusinessRegRoute
  DashboardRoute: typeof DashboardRoute
  DistributorLoginRoute: typeof DistributorLoginRoute
  DroLoginRoute: typeof DroLoginRoute
  GetStartedRoute: typeof GetStartedRoute
  GovServicesRoute: typeof GovServicesRoute
  GstRoute: typeof GstRoute
  LoginRoute: typeof LoginRoute
  MasterDistributorLoginRoute: typeof MasterDistributorLoginRoute
  MoneyTransferRoute: typeof MoneyTransferRoute
  NewServiceRequestRoute: typeof NewServiceRequestRoute
  NotificationsRoute: typeof NotificationsRoute
  PanRoute: typeof PanRoute
  PortalsRoute: typeof PortalsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QcLoginRoute: typeof QcLoginRoute
  RechargeRoute: typeof RechargeRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackApplicationRoute: typeof TrackApplicationRoute
  TransactionsRoute: typeof TransactionsRoute
  TroLoginRoute: typeof TroLoginRoute
  VideoKycRoute: typeof VideoKycRoute
  WalletRoute: typeof WalletRoute
  AccountantChangePasswordRoute: typeof AccountantChangePasswordRoute
  AccountantDashboardRoute: typeof AccountantDashboardRoute
  AccountantMainRechargeRoute: typeof AccountantMainRechargeRoute
  AccountantProfileRoute: typeof AccountantProfileRoute
  AccountantRegistrationsRoute: typeof AccountantRegistrationsRoute
  AccountantServicesRoute: typeof AccountantServicesRoute
  AccountantSettingsRoute: typeof AccountantSettingsRoute
  AccountantWalletRequestsRoute: typeof AccountantWalletRequestsRoute
  AccountantWithdrawalsRoute: typeof AccountantWithdrawalsRoute
  QcApprovedRoute: typeof QcApprovedRoute
  QcChangePasswordRoute: typeof QcChangePasswordRoute
  QcDashboardRoute: typeof QcDashboardRoute
  QcDocumentSearchRoute: typeof QcDocumentSearchRoute
  QcFlaggedRoute: typeof QcFlaggedRoute
  QcKycQueueRoute: typeof QcKycQueueRoute
  QcProfileRoute: typeof QcProfileRoute
  QcReportsRoute: typeof QcReportsRoute
  QcReviewersRoute: typeof QcReviewersRoute
  QcSettingsRoute: typeof QcSettingsRoute
  QcKycReviewIdRoute: typeof QcKycReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-kyc': {
      id: '/video-kyc'
      path: '/video-kyc'
      fullPath: '/video-kyc'
      preLoaderRoute: typeof VideoKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro-login': {
      id: '/tro-login'
      path: '/tro-login'
      fullPath: '/tro-login'
      preLoaderRoute: typeof TroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-application': {
      id: '/track-application'
      path: '/track-application'
      fullPath: '/track-application'
      preLoaderRoute: typeof TrackApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc-login': {
      id: '/qc-login'
      path: '/qc-login'
      fullPath: '/qc-login'
      preLoaderRoute: typeof QcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pan': {
      id: '/pan'
      path: '/pan'
      fullPath: '/pan'
      preLoaderRoute: typeof PanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-service-request': {
      id: '/new-service-request'
      path: '/new-service-request'
      fullPath: '/new-service-request'
      preLoaderRoute: typeof NewServiceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-transfer': {
      id: '/money-transfer'
      path: '/money-transfer'
      fullPath: '/money-transfer'
      preLoaderRoute: typeof MoneyTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-distributor-login': {
      id: '/master-distributor-login'
      path: '/master-distributor-login'
      fullPath: '/master-distributor-login'
      preLoaderRoute: typeof MasterDistributorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov-services': {
      id: '/gov-services'
      path: '/gov-services'
      fullPath: '/gov-services'
      preLoaderRoute: typeof GovServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dro-login': {
      id: '/dro-login'
      path: '/dro-login'
      fullPath: '/dro-login'
      preLoaderRoute: typeof DroLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor-login': {
      id: '/distributor-login'
      path: '/distributor-login'
      fullPath: '/distributor-login'
      preLoaderRoute: typeof DistributorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-reg': {
      id: '/business-reg'
      path: '/business-reg'
      fullPath: '/business-reg'
      preLoaderRoute: typeof BusinessRegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbps': {
      id: '/bbps'
      path: '/bbps'
      fullPath: '/bbps'
      preLoaderRoute: typeof BbpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeps-activation': {
      id: '/aeps-activation'
      path: '/aeps-activation'
      fullPath: '/aeps-activation'
      preLoaderRoute: typeof AepsActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeps': {
      id: '/aeps'
      path: '/aeps'
      fullPath: '/aeps'
      preLoaderRoute: typeof AepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant-login': {
      id: '/accountant-login'
      path: '/accountant-login'
      fullPath: '/accountant-login'
      preLoaderRoute: typeof AccountantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/settings': {
      id: '/qc/settings'
      path: '/qc/settings'
      fullPath: '/qc/settings'
      preLoaderRoute: typeof QcSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/reviewers': {
      id: '/qc/reviewers'
      path: '/qc/reviewers'
      fullPath: '/qc/reviewers'
      preLoaderRoute: typeof QcReviewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/reports': {
      id: '/qc/reports'
      path: '/qc/reports'
      fullPath: '/qc/reports'
      preLoaderRoute: typeof QcReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/profile': {
      id: '/qc/profile'
      path: '/qc/profile'
      fullPath: '/qc/profile'
      preLoaderRoute: typeof QcProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/kyc-queue': {
      id: '/qc/kyc-queue'
      path: '/qc/kyc-queue'
      fullPath: '/qc/kyc-queue'
      preLoaderRoute: typeof QcKycQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/flagged': {
      id: '/qc/flagged'
      path: '/qc/flagged'
      fullPath: '/qc/flagged'
      preLoaderRoute: typeof QcFlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/document-search': {
      id: '/qc/document-search'
      path: '/qc/document-search'
      fullPath: '/qc/document-search'
      preLoaderRoute: typeof QcDocumentSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/dashboard': {
      id: '/qc/dashboard'
      path: '/qc/dashboard'
      fullPath: '/qc/dashboard'
      preLoaderRoute: typeof QcDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/change-password': {
      id: '/qc/change-password'
      path: '/qc/change-password'
      fullPath: '/qc/change-password'
      preLoaderRoute: typeof QcChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/approved': {
      id: '/qc/approved'
      path: '/qc/approved'
      fullPath: '/qc/approved'
      preLoaderRoute: typeof QcApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/withdrawals': {
      id: '/accountant/withdrawals'
      path: '/accountant/withdrawals'
      fullPath: '/accountant/withdrawals'
      preLoaderRoute: typeof AccountantWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/wallet-requests': {
      id: '/accountant/wallet-requests'
      path: '/accountant/wallet-requests'
      fullPath: '/accountant/wallet-requests'
      preLoaderRoute: typeof AccountantWalletRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/settings': {
      id: '/accountant/settings'
      path: '/accountant/settings'
      fullPath: '/accountant/settings'
      preLoaderRoute: typeof AccountantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/services': {
      id: '/accountant/services'
      path: '/accountant/services'
      fullPath: '/accountant/services'
      preLoaderRoute: typeof AccountantServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/registrations': {
      id: '/accountant/registrations'
      path: '/accountant/registrations'
      fullPath: '/accountant/registrations'
      preLoaderRoute: typeof AccountantRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/profile': {
      id: '/accountant/profile'
      path: '/accountant/profile'
      fullPath: '/accountant/profile'
      preLoaderRoute: typeof AccountantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/main-recharge': {
      id: '/accountant/main-recharge'
      path: '/accountant/main-recharge'
      fullPath: '/accountant/main-recharge'
      preLoaderRoute: typeof AccountantMainRechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/dashboard': {
      id: '/accountant/dashboard'
      path: '/accountant/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof AccountantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant/change-password': {
      id: '/accountant/change-password'
      path: '/accountant/change-password'
      fullPath: '/accountant/change-password'
      preLoaderRoute: typeof AccountantChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc/kyc-review/$id': {
      id: '/qc/kyc-review/$id'
      path: '/qc/kyc-review/$id'
      fullPath: '/qc/kyc-review/$id'
      preLoaderRoute: typeof QcKycReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantLoginRoute: AccountantLoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  AepsRoute: AepsRoute,
  AepsActivationRoute: AepsActivationRoute,
  ApplicationsRoute: ApplicationsRoute,
  BbpsRoute: BbpsRoute,
  BusinessRegRoute: BusinessRegRoute,
  DashboardRoute: DashboardRoute,
  DistributorLoginRoute: DistributorLoginRoute,
  DroLoginRoute: DroLoginRoute,
  GetStartedRoute: GetStartedRoute,
  GovServicesRoute: GovServicesRoute,
  GstRoute: GstRoute,
  LoginRoute: LoginRoute,
  MasterDistributorLoginRoute: MasterDistributorLoginRoute,
  MoneyTransferRoute: MoneyTransferRoute,
  NewServiceRequestRoute: NewServiceRequestRoute,
  NotificationsRoute: NotificationsRoute,
  PanRoute: PanRoute,
  PortalsRoute: PortalsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QcLoginRoute: QcLoginRoute,
  RechargeRoute: RechargeRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackApplicationRoute: TrackApplicationRoute,
  TransactionsRoute: TransactionsRoute,
  TroLoginRoute: TroLoginRoute,
  VideoKycRoute: VideoKycRoute,
  WalletRoute: WalletRoute,
  AccountantChangePasswordRoute: AccountantChangePasswordRoute,
  AccountantDashboardRoute: AccountantDashboardRoute,
  AccountantMainRechargeRoute: AccountantMainRechargeRoute,
  AccountantProfileRoute: AccountantProfileRoute,
  AccountantRegistrationsRoute: AccountantRegistrationsRoute,
  AccountantServicesRoute: AccountantServicesRoute,
  AccountantSettingsRoute: AccountantSettingsRoute,
  AccountantWalletRequestsRoute: AccountantWalletRequestsRoute,
  AccountantWithdrawalsRoute: AccountantWithdrawalsRoute,
  QcApprovedRoute: QcApprovedRoute,
  QcChangePasswordRoute: QcChangePasswordRoute,
  QcDashboardRoute: QcDashboardRoute,
  QcDocumentSearchRoute: QcDocumentSearchRoute,
  QcFlaggedRoute: QcFlaggedRoute,
  QcKycQueueRoute: QcKycQueueRoute,
  QcProfileRoute: QcProfileRoute,
  QcReportsRoute: QcReportsRoute,
  QcReviewersRoute: QcReviewersRoute,
  QcSettingsRoute: QcSettingsRoute,
  QcKycReviewIdRoute: QcKycReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
